import { z } from 'zod';
import { UuidSchema } from './primitives';
import { LocalizedTextSchema } from './content';

// Media, video and link primitives shared by section content, the admin and the public
// loaders (UI v2). One schema per shape, here, per CLAUDE.md §8.

// ── Links ───────────────────────────────────────────────────────────────────────

/**
 * An href a CMS editor may author into a button or CTA: an in-page anchor (`#inquiry`) or
 * a site-relative logical path (`/contact#inquiry`, `/portfolio`), nothing else.
 *
 * `(?!/)` after the leading slash is load-bearing: `//evil.example` is a scheme-relative
 * URL — an off-site link wearing a relative path's clothes. No query strings either: the
 * only query-bearing links on the site (catalog facets) are generated by code.
 */
export const SafeHrefSchema = z
  .string()
  .trim()
  .max(200)
  .regex(
    /^(#[a-z][a-z0-9-]*|\/(?!\/)[a-z0-9/_-]*(#[a-z][a-z0-9-]*)?)$/,
    'must be #anchor or /path',
  );

// ── Video ───────────────────────────────────────────────────────────────────────

/** Cloudflare Stream video UID. */
export const StreamUidSchema = z.string().regex(/^[a-f0-9]{32}$/, 'not a Stream UID');

/**
 * A self-hosted MP4 under /media — the temporary path while Stream is unprovisioned
 * (KAN-20). This allow-list IS the fence of exception EXC-009: no other origin, no other
 * directory, no traversal (the character class admits no `.` before the extension).
 */
export const StaticVideoPathSchema = z
  .string()
  .regex(/^\/media\/[a-z0-9][a-z0-9/_-]*\.mp4$/, 'must be a /media/*.mp4 path');

/** Longest clip window. The design loops 1–4 s windows; 30 s is generous and bounded. */
export const MAX_CLIP_SECONDS = 30;

const Seconds = z.number().min(0).max(600);

/**
 * One background clip: exactly ONE source (a Stream UID or a static path), optionally
 * narrowed to a [startS, endS) window of it — the design plays short windows of one
 * showreel on different pages ("so this page doesn't replay the homepage opening").
 */
export const VideoClipSchema = z
  .object({
    streamUid: StreamUidSchema.optional(),
    path: StaticVideoPathSchema.optional(),
    startS: Seconds.optional(),
    endS: Seconds.optional(),
  })
  .superRefine((v, ctx) => {
    if ((v.streamUid === undefined) === (v.path === undefined)) {
      ctx.addIssue({ code: z.ZodIssueCode.custom, message: 'exactly one of streamUid or path' });
    }
    if ((v.startS === undefined) !== (v.endS === undefined)) {
      ctx.addIssue({
        code: z.ZodIssueCode.custom,
        path: ['endS'],
        message: 'startS and endS come together',
      });
    } else if (v.startS !== undefined && v.endS !== undefined) {
      if (!(v.endS > v.startS)) {
        ctx.addIssue({
          code: z.ZodIssueCode.custom,
          path: ['endS'],
          message: 'endS must be after startS',
        });
      } else if (v.endS - v.startS > MAX_CLIP_SECONDS) {
        ctx.addIssue({
          code: z.ZodIssueCode.custom,
          path: ['endS'],
          message: `a clip window is at most ${MAX_CLIP_SECONDS} s`,
        });
      }
    }
  });
export type VideoClip = z.infer<typeof VideoClipSchema>;

// ── Images ──────────────────────────────────────────────────────────────────────

/**
 * Registry key of a build-time still (src/assets/media/stills/…), resolved by
 * src/lib/media/static.ts through import.meta.glob so <Picture> processes it as an ESM
 * image (real AVIF/WebP via /_image). Lowercase path segments only; no `.` before the
 * extension, so `..` cannot appear.
 */
export const StaticMediaKeySchema = z
  .string()
  .regex(/^stills\/[a-z0-9][a-z0-9/_-]*\.(jpe?g|png|webp|avif)$/, 'not a stills/… key');

/** A reference to a media_assets row, with an optional per-use alt override. */
export const MediaRefSchema = z.object({
  mediaId: UuidSchema,
  altOverride: LocalizedTextSchema.optional(),
});
export type MediaRef = z.infer<typeof MediaRefSchema>;

/** Where a cropped video/poster anchors. An enum of classes — never free CSS (CSP). */
export const ObjectPositionSchema = z.enum(['center', 'center-42', 'top', 'bottom']);

// ── Accent ranges ───────────────────────────────────────────────────────────────

const AccentRange = z
  .object({
    /** 0-based index of the first accented word. */
    from: z.number().int().min(0).max(30),
    /** Exclusive end; omitted = accent runs to the end of the line. */
    to: z.number().int().min(1).max(31).optional(),
  })
  .refine((r) => r.to === undefined || r.to > r.from, { message: 'to must be after from' });

/**
 * Which words of a heading carry the accent colour, per locale. A word RANGE, not a
 * start index: the design accents the middle of lines ("Ideas that <em>leave the
 * brain</em> and land in the world"), which a from-here-to-the-end index cannot say.
 */
export const AccentSchema = z.object({ en: AccentRange.optional(), ar: AccentRange.optional() });
export type Accent = z.infer<typeof AccentSchema>;
