import type { LocalizedDoc } from '@schemas/tiptap';
import type { ContentStatus } from '@schemas/primitives';
import type { VideoClip } from '@schemas/media';
import { renderTiptapToHtml } from '@/lib/content/tiptap';
import { ValidationError } from '../errors';
import type { ResourcePayload } from '../resource';

// What the resource configs share (Admin v2 W0: one module per entity in this
// directory): the column allowlist, the derived columns, the go-live rules and the
// tenant fence on links. Nothing here is a resource; ./index.ts registers those.

export type Input = ResourcePayload;

/**
 * camelCase input → snake_case column patch.
 *
 * This is the allowlist that makes mass-assignment impossible: a client can send
 * `{"tenant_id": "<someone else's>"}` or `{"version": 999}` all it likes, because only
 * keys named in `map` are ever copied into the object handed to the query builder.
 * `undefined` is skipped so a PATCH touches exactly the fields it sent — `null` is
 * kept, because "clear this field" is a real edit.
 */
export function pick(input: Input, map: Record<string, string>): Input {
  const out: Input = {};
  for (const [key, column] of Object.entries(map)) {
    if (key in input && input[key] !== undefined) out[column] = input[key];
  }
  return out;
}

/** Locale-keyed Tiptap JSON → locale-keyed sanitised HTML (the render-time cache). */
function deriveBodyHtml(body: unknown): Record<string, string> | null {
  if (!body || typeof body !== 'object') return null;
  const doc = body as Partial<LocalizedDoc>;
  const out: Record<string, string> = {};
  if (doc.en) out['en'] = renderTiptapToHtml(doc.en);
  if (doc.ar) out['ar'] = renderTiptapToHtml(doc.ar);
  return out;
}

/**
 * Adds the derived HTML cache alongside the stored JSON.
 *
 * Both are written in the same statement on purpose. If `body_html` were regenerated
 * lazily at render time, the public Tier-A page would be re-sanitising on every cache
 * miss (a per-request cost on the latency-critical path), and if it were regenerated by
 * a separate call the two could drift — leaving stored JSON that says one thing and
 * cached HTML that says another, with the HTML being what visitors actually see.
 */
export function withBodyHtml(values: Input, input: Input): Input {
  if (!('body' in input) || input['body'] === undefined) return values;
  return { ...values, body_html: deriveBodyHtml(input['body']) };
}

export const statusOf = (input: Input): ContentStatus | undefined =>
  typeof input['status'] === 'string' ? (input['status'] as ContentStatus) : undefined;

/**
 * A save with status `published` carries a publish date; the kernel drops it again when the
 * row already has one (resource.ts PATCH), so the FIRST publish date is never rewritten
 * (truthful dates, Pillar 3).
 */
export function publishStamp(values: Input): Input {
  return values['status'] === 'published'
    ? { ...values, published_at: new Date().toISOString() }
    : values;
}

export function requireBilingual(row: Input, column: string, label: string): void {
  const value = row[column];
  const record = (value ?? {}) as Record<string, unknown>;
  if (!record['en'] || !record['ar']) {
    throw new ValidationError(`${label} must have both English and Arabic before publishing`);
  }
}

/**
 * The app half of the placeholder rule (0025 is the database half, production only):
 * design-delivery samples never go live through the admin, in any environment — seeded
 * staging rows are published by the seed, not by an editor.
 */
export function refusePlaceholder(row: Input, what: string): void {
  if (row['is_placeholder'] === true) {
    throw new ValidationError(
      `this ${what} is placeholder content — replace it and untick “Placeholder” before it goes live`,
      'isPlaceholder',
    );
  }
}

/** A clip's wire shape → its four columns (`null` clears all four). */
export function clipColumns(clip: VideoClip | null, prefix: string, video: string): Input {
  return {
    [`${prefix}${video}_uid`]: clip?.streamUid ?? null,
    [`${prefix}${video}_path`]: clip?.path ?? null,
    [`${prefix}start_s`]: clip?.startS ?? null,
    [`${prefix}end_s`]: clip?.endS ?? null,
  };
}

/** Four clip columns → the wire shape, or null when there is no source. */
export function clipOfColumns(
  uid: unknown,
  path: unknown,
  start: unknown,
  end: unknown,
): Record<string, unknown> | null {
  if (!uid && !path) return null;
  const clip: Record<string, unknown> = {};
  if (uid) clip['streamUid'] = uid;
  if (path) clip['path'] = path;
  if (start !== null && start !== undefined) clip['startS'] = Number(start);
  if (end !== null && end !== undefined) clip['endS'] = Number(end);
  return clip;
}

/**
 * A path-only clip (disciplines, services — 0028 has no Stream-uid column there) → its
 * three preview_* columns; `null` clears them. PathClipSchema has already refused a
 * Stream uid, so there is nothing to drop.
 */
function previewPathColumns(clip: VideoClip | null): Input {
  return {
    preview_video_path: clip?.path ?? null,
    preview_start_s: clip?.startS ?? null,
    preview_end_s: clip?.endS ?? null,
  };
}

/** `clip` (the wire name) → the preview_* patch, only when the payload carries it. */
export function withPreviewPath(values: Input, input: Input): Input {
  const clip = input['clip'];
  return clip === undefined
    ? values
    : { ...values, ...previewPathColumns((clip as VideoClip | null) ?? null) };
}

/** The stored preview_* columns → the clip the form edits (returned as `preview`). */
export function withPreviewField(row: Input): Input {
  return {
    ...row,
    preview: clipOfColumns(
      null,
      row['preview_video_path'],
      row['preview_start_s'],
      row['preview_end_s'],
    ),
  };
}

/** A result card still showing the design's placeholder figure ("XXM", "+XX%"). */
export function refusePlaceholderFigures(row: Input): void {
  const results = Array.isArray(row['results']) ? (row['results'] as Input[]) : [];
  if (results.some((r) => /X{2,}/i.test(String(r['value'] ?? '')))) {
    throw new ValidationError('a result card still shows a placeholder figure (XX)', 'results');
  }
}

export const bySortOrder = (a: Input, b: Input) =>
  Number(a['sort_order']) - Number(b['sort_order']);

type Db = import('@supabase/supabase-js').SupabaseClient;
type Auth = import('@/lib/auth/types').AuthContext;

/**
 * A link that must name a row of the caller's OWN tenant. A bare foreign key accepts
 * another tenant's id. For the 0028 posters the database cannot say otherwise (a media
 * policy that read the content tables would recurse), and for a discipline its RESTRICTIVE
 * WITH CHECK would only answer a bare 403 — so the Worker checks first, under the caller's
 * RLS and the tenant predicate, and says which field is wrong. Only when the write sets it.
 */
export async function assertLinkInTenant(
  ctx: { auth: Auth; sb: Db; changed: Input },
  link: { column: string; table: string; field: string; message: string; image?: boolean },
): Promise<void> {
  const id = ctx.changed[link.column];
  if (id === undefined || id === null) return;
  let q = ctx.sb
    .from(link.table)
    .select('id')
    .eq('tenant_id', ctx.auth.tenantId)
    .eq('id', String(id));
  if (link.image) q = q.eq('kind', 'image');
  const { data, error } = await q.maybeSingle();
  if (error) throw new Error(`check ${link.table}: ${error.message}`);
  if (!data) throw new ValidationError(link.message, link.field);
}

export const POSTER_LINK = {
  column: 'poster_media_id',
  table: 'media_assets',
  field: 'posterMediaId',
  message: 'choose the poster from this site’s media library (an image)',
  image: true,
} as const;
