import { UUID, VALID_BILINGUAL, type Case } from '../harness';

// Collections: clients, testimonials, team, numbers and certifications (UI v2 content
// model, 0020–0025). Each is authored by Content Creator; deleting is Admin only.

export const cases: readonly Case[] = [
  {
    name: 'clients list',
    load: () => import('@/pages/api/admin/clients/index'),
    method: 'GET',
    url: '/api/admin/clients',
    allow: ['admin', 'content_creator', 'seo'],
  },
  {
    name: 'clients create',
    load: () => import('@/pages/api/admin/clients/index'),
    method: 'POST',
    url: '/api/admin/clients',
    body: { slug: 'neom', name: VALID_BILINGUAL },
    allow: ['admin', 'content_creator'],
  },
  {
    name: 'clients read one',
    load: () => import('@/pages/api/admin/clients/[id]'),
    method: 'GET',
    url: `/api/admin/clients/${UUID}`,
    allow: ['admin', 'content_creator', 'seo'],
  },
  {
    name: 'clients clear for disclosure (visible = publish)',
    load: () => import('@/pages/api/admin/clients/[id]'),
    method: 'PATCH',
    url: `/api/admin/clients/${UUID}`,
    body: { visible: true, version: 1 },
    allow: ['admin', 'content_creator'],
  },
  {
    name: 'clients delete',
    load: () => import('@/pages/api/admin/clients/[id]'),
    method: 'DELETE',
    url: `/api/admin/clients/${UUID}`,
    allow: ['admin'],
  },
  {
    name: 'clients reorder',
    load: () => import('@/pages/api/admin/clients/reorder'),
    method: 'POST',
    url: '/api/admin/clients/reorder',
    body: { items: [{ id: UUID, sortOrder: 10 }] },
    allow: ['admin', 'content_creator'],
  },
  {
    name: 'testimonials list',
    load: () => import('@/pages/api/admin/testimonials/index'),
    method: 'GET',
    url: '/api/admin/testimonials',
    allow: ['admin', 'content_creator'],
  },
  {
    name: 'testimonials create',
    load: () => import('@/pages/api/admin/testimonials/index'),
    method: 'POST',
    url: '/api/admin/testimonials',
    body: { slug: 'q', quote: VALID_BILINGUAL, authorName: VALID_BILINGUAL },
    allow: ['admin', 'content_creator'],
  },
  {
    name: 'testimonials read one',
    load: () => import('@/pages/api/admin/testimonials/[id]'),
    method: 'GET',
    url: `/api/admin/testimonials/${UUID}`,
    allow: ['admin', 'content_creator'],
  },
  {
    name: 'testimonials publish',
    load: () => import('@/pages/api/admin/testimonials/[id]'),
    method: 'PATCH',
    url: `/api/admin/testimonials/${UUID}`,
    body: { status: 'published', version: 1 },
    allow: ['admin', 'content_creator'],
  },
  {
    name: 'testimonials delete',
    load: () => import('@/pages/api/admin/testimonials/[id]'),
    method: 'DELETE',
    url: `/api/admin/testimonials/${UUID}`,
    allow: ['admin'],
  },
  {
    name: 'testimonials reorder',
    load: () => import('@/pages/api/admin/testimonials/reorder'),
    method: 'POST',
    url: '/api/admin/testimonials/reorder',
    body: { items: [{ id: UUID, sortOrder: 10 }] },
    allow: ['admin', 'content_creator'],
  },
  {
    name: 'team list',
    load: () => import('@/pages/api/admin/team/index'),
    method: 'GET',
    url: '/api/admin/team',
    // Authors are read by the post and service editors too, and by SEO for their meta.
    allow: ['admin', 'content_creator', 'seo'],
  },
  {
    name: 'team create (leadership fields)',
    load: () => import('@/pages/api/admin/team/index'),
    method: 'POST',
    url: '/api/admin/team',
    body: { slug: 'leader-1', name: VALID_BILINGUAL, isLeadership: true },
    allow: ['admin', 'content_creator'],
  },
  {
    name: 'team read one',
    load: () => import('@/pages/api/admin/team/[id]'),
    method: 'GET',
    url: `/api/admin/team/${UUID}`,
    allow: ['admin', 'content_creator', 'seo'],
  },
  {
    name: 'team update',
    load: () => import('@/pages/api/admin/team/[id]'),
    method: 'PATCH',
    url: `/api/admin/team/${UUID}`,
    body: { name: VALID_BILINGUAL, version: 1 },
    allow: ['admin', 'content_creator'],
  },
  {
    name: 'team delete',
    load: () => import('@/pages/api/admin/team/[id]'),
    method: 'DELETE',
    url: `/api/admin/team/${UUID}`,
    allow: ['admin'],
  },
  {
    name: 'team reorder',
    load: () => import('@/pages/api/admin/team/reorder'),
    method: 'POST',
    url: '/api/admin/team/reorder',
    body: { items: [{ id: UUID, sortOrder: 10 }] },
    allow: ['admin', 'content_creator'],
  },
  {
    name: 'statistics list',
    load: () => import('@/pages/api/admin/statistics/index'),
    method: 'GET',
    url: '/api/admin/statistics',
    allow: ['admin', 'content_creator'],
  },
  {
    name: 'statistics create (count-up value)',
    load: () => import('@/pages/api/admin/statistics/index'),
    method: 'POST',
    url: '/api/admin/statistics',
    body: { slug: 'brands', label: VALID_BILINGUAL, valueNumeric: 80, valueSuffix: '+' },
    allow: ['admin', 'content_creator'],
  },
  {
    name: 'statistics read one',
    load: () => import('@/pages/api/admin/statistics/[id]'),
    method: 'GET',
    url: `/api/admin/statistics/${UUID}`,
    allow: ['admin', 'content_creator'],
  },
  {
    name: 'statistics update',
    load: () => import('@/pages/api/admin/statistics/[id]'),
    method: 'PATCH',
    url: `/api/admin/statistics/${UUID}`,
    body: { label: VALID_BILINGUAL, version: 1 },
    allow: ['admin', 'content_creator'],
  },
  {
    name: 'statistics delete',
    load: () => import('@/pages/api/admin/statistics/[id]'),
    method: 'DELETE',
    url: `/api/admin/statistics/${UUID}`,
    allow: ['admin'],
  },
  {
    name: 'statistics reorder',
    load: () => import('@/pages/api/admin/statistics/reorder'),
    method: 'POST',
    url: '/api/admin/statistics/reorder',
    body: { items: [{ id: UUID, sortOrder: 10 }] },
    allow: ['admin', 'content_creator'],
  },
  {
    name: 'certifications list',
    load: () => import('@/pages/api/admin/certifications/index'),
    method: 'GET',
    url: '/api/admin/certifications',
    allow: ['admin', 'content_creator'],
  },
  {
    name: 'certifications create',
    load: () => import('@/pages/api/admin/certifications/index'),
    method: 'POST',
    url: '/api/admin/certifications',
    body: { slug: 'iso-9001', name: VALID_BILINGUAL },
    allow: ['admin', 'content_creator'],
  },
  {
    name: 'certifications read one',
    load: () => import('@/pages/api/admin/certifications/[id]'),
    method: 'GET',
    url: `/api/admin/certifications/${UUID}`,
    allow: ['admin', 'content_creator'],
  },
  {
    name: 'certifications update',
    load: () => import('@/pages/api/admin/certifications/[id]'),
    method: 'PATCH',
    url: `/api/admin/certifications/${UUID}`,
    body: { name: VALID_BILINGUAL, version: 1 },
    allow: ['admin', 'content_creator'],
  },
  {
    name: 'certifications delete',
    load: () => import('@/pages/api/admin/certifications/[id]'),
    method: 'DELETE',
    url: `/api/admin/certifications/${UUID}`,
    allow: ['admin'],
  },
  {
    name: 'certifications reorder',
    load: () => import('@/pages/api/admin/certifications/reorder'),
    method: 'POST',
    url: '/api/admin/certifications/reorder',
    body: { items: [{ id: UUID, sortOrder: 10 }] },
    allow: ['admin', 'content_creator'],
  },
];
