-- GENERATED by scripts/gen-seeds.mjs from supabase/seed-data/*.json — DO NOT EDIT.
-- Change the JSON, then run `npm run seed:gen`.
-- Seed for PRODUCTION: the same rows as supabase/seed.sql, with every design placeholder
-- demoted to draft / hidden so editors can replace and publish it. Safe to re-run: every
-- statement is conflict → do nothing, so it never overwrites an editor's change.
-- Apply: psql -v ON_ERROR_STOP=1 -f supabase/seeds/production.sql

begin;

-- tenants (00-tenant.json)
insert into public.tenants (id, name, primary_domain) values
  ('00000000-0000-0000-0000-0000000000b1', 'Braiin Station', 'www.braiinstation.com')
on conflict (id) do nothing;

-- site_settings (00-tenant.json)
insert into public.site_settings (tenant_id, identity) values
  ('00000000-0000-0000-0000-0000000000b1', '{"title":"Braiin Station","default_locale":"en"}'::jsonb)
on conflict (tenant_id) do nothing;

-- site_profile (00-tenant.json)
insert into public.site_profile (tenant_id, brand_name, contact_email, location, address_locality, address_country, founded_year, socials, accepting_applications) values
  ('00000000-0000-0000-0000-0000000000b1', '{"en":"Braiin Statiion","ar":"بريّن ستيشن"}'::jsonb, 'hello@braiinstatiion.com', '{"en":"Jeddah, Saudi Arabia","ar":"جدة، المملكة العربية السعودية"}'::jsonb, '{"en":"Jeddah","ar":"جدة"}'::jsonb, 'SA', 2019, '[{"network":"instagram","handle":"@braiinstatiion","url":"https://instagram.com/braiinstatiion"},{"network":"linkedin","handle":"@braiin-statiion","url":"https://linkedin.com/company/braiin-statiion"},{"network":"behance","handle":"@braiinstatiion","url":"https://behance.net/braiinstatiion"},{"network":"youtube","handle":"@braiinstatiion","url":"https://youtube.com/@braiinstatiion"}]'::jsonb, false)
on conflict (tenant_id) do nothing;

-- services (10-services.json)
insert into public.services (tenant_id, slug, title, blurb, status, is_teaser, sort_order) values
  ('00000000-0000-0000-0000-0000000000b1', 'branding', '{"en":"Branding","ar":"الهوية البصرية"}'::jsonb, '{"en":"Identity systems that make brands unmistakable.","ar":"أنظمة هوية تجعل العلامات لا تُنسى."}'::jsonb, 'published', false, 1),
  ('00000000-0000-0000-0000-0000000000b1', 'animations', '{"en":"Animations","ar":"الرسوم المتحركة"}'::jsonb, '{"en":"Characters and stories brought to life.","ar":"شخصيات وقصص تنبض بالحياة."}'::jsonb, 'published', false, 2),
  ('00000000-0000-0000-0000-0000000000b1', 'motion-graphics', '{"en":"Motion Graphics","ar":"موشن جرافيك"}'::jsonb, '{"en":"Design in motion for screens of every size.","ar":"تصميم متحرك لكل الشاشات."}'::jsonb, 'published', false, 3),
  ('00000000-0000-0000-0000-0000000000b1', 'videography', '{"en":"Videography","ar":"إنتاج الفيديو"}'::jsonb, '{"en":"Cinematic production end to end.","ar":"إنتاج سينمائي من الفكرة إلى التسليم."}'::jsonb, 'published', false, 4),
  ('00000000-0000-0000-0000-0000000000b1', 'photography', '{"en":"Photography","ar":"التصوير الفوتوغرافي"}'::jsonb, '{"en":"Images that sell the moment.","ar":"صور تروي اللحظة."}'::jsonb, 'published', false, 5),
  ('00000000-0000-0000-0000-0000000000b1', 'montage', '{"en":"Montage","ar":"المونتاج"}'::jsonb, '{"en":"Editing that gives footage its rhythm.","ar":"مونتاج يمنح اللقطات إيقاعها."}'::jsonb, 'published', false, 6),
  ('00000000-0000-0000-0000-0000000000b1', 'event-planning', '{"en":"Event Planning","ar":"تنظيم الفعاليات"}'::jsonb, '{"en":"Experiences planned down to the detail.","ar":"تجارب مُخطَّطة حتى أدق التفاصيل."}'::jsonb, 'published', false, 7),
  ('00000000-0000-0000-0000-0000000000b1', 'advertising', '{"en":"Advertising","ar":"الإعلانات"}'::jsonb, '{"en":"Campaigns that move audiences.","ar":"حملات تحرّك الجمهور."}'::jsonb, 'published', false, 8),
  ('00000000-0000-0000-0000-0000000000b1', 'social-media', '{"en":"Social Media","ar":"وسائل التواصل"}'::jsonb, '{"en":"Always-on presence that converts.","ar":"حضور دائم يحقق النتائج."}'::jsonb, 'published', false, 9),
  ('00000000-0000-0000-0000-0000000000b1', 'web-development', '{"en":"Web Development","ar":"تطوير المواقع"}'::jsonb, '{"en":"Fast, secure, accessible sites.","ar":"مواقع سريعة وآمنة وسهلة الوصول."}'::jsonb, 'published', false, 10),
  ('00000000-0000-0000-0000-0000000000b1', 'seo-geo-aeo', '{"en":"SEO / GEO / AEO","ar":"تحسين محركات البحث"}'::jsonb, '{"en":"Be found by people and AI answer engines.","ar":"ظهور أمام الناس ومحركات الإجابة بالذكاء الاصطناعي."}'::jsonb, 'published', false, 11),
  ('00000000-0000-0000-0000-0000000000b1', 'music', '{"en":"Music","ar":"الموسيقى"}'::jsonb, '{"en":"Original sound and scoring.","ar":"موسيقى وتلحين أصلي."}'::jsonb, 'published', false, 12),
  ('00000000-0000-0000-0000-0000000000b1', 'merchandise', '{"en":"Merchandise","ar":"المنتجات الترويجية"}'::jsonb, '{"en":"Branded products people keep.","ar":"منتجات تحمل العلامة ويحتفظ بها الناس."}'::jsonb, 'published', false, 13),
  ('00000000-0000-0000-0000-0000000000b1', 'gaming', '{"en":"Gaming","ar":"الألعاب"}'::jsonb, '{"en":"Coming soon.","ar":"قريبًا."}'::jsonb, 'published', true, 14)
on conflict (tenant_id, slug) do nothing;

-- pages (20-pages.json)
insert into public.pages (tenant_id, slug, title, status) values
  ('00000000-0000-0000-0000-0000000000b1', 'home', '{"en":"Home","ar":"الرئيسية"}'::jsonb, 'published'),
  ('00000000-0000-0000-0000-0000000000b1', 'about', '{"en":"About","ar":"من نحن"}'::jsonb, 'published'),
  ('00000000-0000-0000-0000-0000000000b1', 'contact', '{"en":"Contact us","ar":"تواصل معنا"}'::jsonb, 'published'),
  ('00000000-0000-0000-0000-0000000000b1', 'portfolio', '{"en":"Our Work","ar":"أعمالنا"}'::jsonb, 'published'),
  ('00000000-0000-0000-0000-0000000000b1', 'portfolio-all', '{"en":"All projects","ar":"كل المشاريع"}'::jsonb, 'published'),
  ('00000000-0000-0000-0000-0000000000b1', 'join', '{"en":"Join us","ar":"انضم إلينا"}'::jsonb, 'published')
on conflict (tenant_id, slug) do nothing;

-- navigation (25-navigation.json)
insert into public.navigation (tenant_id, id, location, label, href, sort_order, visible, is_key)
  select '00000000-0000-0000-0000-0000000000b1', '00000000-0000-4000-8000-00000000a101', 'header', '{"en":"Home","ar":"الرئيسية"}'::jsonb, '/', 1, true, false
  where not exists (select 1 from public.navigation
                    where tenant_id = '00000000-0000-0000-0000-0000000000b1' and location = 'header' and id not in ('00000000-0000-4000-8000-00000000a101', '00000000-0000-4000-8000-00000000a102', '00000000-0000-4000-8000-00000000a103', '00000000-0000-4000-8000-00000000a104', '00000000-0000-4000-8000-00000000a105'))
on conflict (id) do nothing;
insert into public.navigation (tenant_id, id, location, label, href, sort_order, visible, is_key)
  select '00000000-0000-0000-0000-0000000000b1', '00000000-0000-4000-8000-00000000a102', 'header', '{"en":"About","ar":"من نحن"}'::jsonb, '/about', 2, true, false
  where not exists (select 1 from public.navigation
                    where tenant_id = '00000000-0000-0000-0000-0000000000b1' and location = 'header' and id not in ('00000000-0000-4000-8000-00000000a101', '00000000-0000-4000-8000-00000000a102', '00000000-0000-4000-8000-00000000a103', '00000000-0000-4000-8000-00000000a104', '00000000-0000-4000-8000-00000000a105'))
on conflict (id) do nothing;
insert into public.navigation (tenant_id, id, location, label, href, sort_order, visible, is_key)
  select '00000000-0000-0000-0000-0000000000b1', '00000000-0000-4000-8000-00000000a103', 'header', '{"en":"Our Work","ar":"أعمالنا"}'::jsonb, '/portfolio', 3, true, false
  where not exists (select 1 from public.navigation
                    where tenant_id = '00000000-0000-0000-0000-0000000000b1' and location = 'header' and id not in ('00000000-0000-4000-8000-00000000a101', '00000000-0000-4000-8000-00000000a102', '00000000-0000-4000-8000-00000000a103', '00000000-0000-4000-8000-00000000a104', '00000000-0000-4000-8000-00000000a105'))
on conflict (id) do nothing;
insert into public.navigation (tenant_id, id, location, label, href, sort_order, visible, is_key)
  select '00000000-0000-0000-0000-0000000000b1', '00000000-0000-4000-8000-00000000a104', 'header', '{"en":"Services","ar":"الخدمات"}'::jsonb, '/#services', 4, true, false
  where not exists (select 1 from public.navigation
                    where tenant_id = '00000000-0000-0000-0000-0000000000b1' and location = 'header' and id not in ('00000000-0000-4000-8000-00000000a101', '00000000-0000-4000-8000-00000000a102', '00000000-0000-4000-8000-00000000a103', '00000000-0000-4000-8000-00000000a104', '00000000-0000-4000-8000-00000000a105'))
on conflict (id) do nothing;
insert into public.navigation (tenant_id, id, location, label, href, sort_order, visible, is_key)
  select '00000000-0000-0000-0000-0000000000b1', '00000000-0000-4000-8000-00000000a105', 'header', '{"en":"Contact us","ar":"تواصل معنا"}'::jsonb, '/contact', 5, true, true
  where not exists (select 1 from public.navigation
                    where tenant_id = '00000000-0000-0000-0000-0000000000b1' and location = 'header' and id not in ('00000000-0000-4000-8000-00000000a101', '00000000-0000-4000-8000-00000000a102', '00000000-0000-4000-8000-00000000a103', '00000000-0000-4000-8000-00000000a104', '00000000-0000-4000-8000-00000000a105'))
on conflict (id) do nothing;

-- navigation (25-navigation.json)
insert into public.navigation (tenant_id, id, location, label, href, sort_order, visible, is_key)
  select '00000000-0000-0000-0000-0000000000b1', '00000000-0000-4000-8000-00000000a201', 'footer', '{"en":"Services","ar":"الخدمات"}'::jsonb, '/services', 1, true, false
  where not exists (select 1 from public.navigation
                    where tenant_id = '00000000-0000-0000-0000-0000000000b1' and location = 'footer' and id not in ('00000000-0000-4000-8000-00000000a201', '00000000-0000-4000-8000-00000000a202', '00000000-0000-4000-8000-00000000a203', '00000000-0000-4000-8000-00000000a204', '00000000-0000-4000-8000-00000000a205'))
on conflict (id) do nothing;
insert into public.navigation (tenant_id, id, location, label, href, sort_order, visible, is_key)
  select '00000000-0000-0000-0000-0000000000b1', '00000000-0000-4000-8000-00000000a202', 'footer', '{"en":"Our Work","ar":"أعمالنا"}'::jsonb, '/portfolio', 2, true, false
  where not exists (select 1 from public.navigation
                    where tenant_id = '00000000-0000-0000-0000-0000000000b1' and location = 'footer' and id not in ('00000000-0000-4000-8000-00000000a201', '00000000-0000-4000-8000-00000000a202', '00000000-0000-4000-8000-00000000a203', '00000000-0000-4000-8000-00000000a204', '00000000-0000-4000-8000-00000000a205'))
on conflict (id) do nothing;
insert into public.navigation (tenant_id, id, location, label, href, sort_order, visible, is_key)
  select '00000000-0000-0000-0000-0000000000b1', '00000000-0000-4000-8000-00000000a203', 'footer', '{"en":"Insights","ar":"المعرفة"}'::jsonb, '/creative-knowledge', 3, true, false
  where not exists (select 1 from public.navigation
                    where tenant_id = '00000000-0000-0000-0000-0000000000b1' and location = 'footer' and id not in ('00000000-0000-4000-8000-00000000a201', '00000000-0000-4000-8000-00000000a202', '00000000-0000-4000-8000-00000000a203', '00000000-0000-4000-8000-00000000a204', '00000000-0000-4000-8000-00000000a205'))
on conflict (id) do nothing;
insert into public.navigation (tenant_id, id, location, label, href, sort_order, visible, is_key)
  select '00000000-0000-0000-0000-0000000000b1', '00000000-0000-4000-8000-00000000a204', 'footer', '{"en":"About","ar":"من نحن"}'::jsonb, '/about', 4, true, false
  where not exists (select 1 from public.navigation
                    where tenant_id = '00000000-0000-0000-0000-0000000000b1' and location = 'footer' and id not in ('00000000-0000-4000-8000-00000000a201', '00000000-0000-4000-8000-00000000a202', '00000000-0000-4000-8000-00000000a203', '00000000-0000-4000-8000-00000000a204', '00000000-0000-4000-8000-00000000a205'))
on conflict (id) do nothing;
insert into public.navigation (tenant_id, id, location, label, href, sort_order, visible, is_key)
  select '00000000-0000-0000-0000-0000000000b1', '00000000-0000-4000-8000-00000000a205', 'footer', '{"en":"Contact","ar":"تواصل معنا"}'::jsonb, '/contact', 5, true, false
  where not exists (select 1 from public.navigation
                    where tenant_id = '00000000-0000-0000-0000-0000000000b1' and location = 'footer' and id not in ('00000000-0000-4000-8000-00000000a201', '00000000-0000-4000-8000-00000000a202', '00000000-0000-4000-8000-00000000a203', '00000000-0000-4000-8000-00000000a204', '00000000-0000-4000-8000-00000000a205'))
on conflict (id) do nothing;

-- portfolio (30-legacy-demo.json)
insert into public.portfolio (tenant_id, slug, title, summary, status, sort_order) values
  ('00000000-0000-0000-0000-0000000000b1', 'riyadh-season-launch', '{"en":"Riyadh Season Launch","ar":"إطلاق موسم الرياض"}'::jsonb, '{"en":"A full-funnel campaign — brand film, motion graphics, and always-on social.","ar":"حملة متكاملة — فيلم للعلامة، وموشن جرافيك، وحضور دائم على وسائل التواصل."}'::jsonb, 'draft', 1),
  ('00000000-0000-0000-0000-0000000000b1', 'cafe-rebrand', '{"en":"Specialty Café Rebrand","ar":"إعادة هوية مقهى مختص"}'::jsonb, '{"en":"A new identity system, packaging, and storefront photography.","ar":"نظام هوية جديد، وتغليف، وتصوير للواجهة."}'::jsonb, 'draft', 2),
  ('00000000-0000-0000-0000-0000000000b1', 'fintech-product-film', '{"en":"Fintech Product Film","ar":"فيلم منتج لشركة تقنية مالية"}'::jsonb, '{"en":"Scriptwriting, cinematic production, and a 60-second cutdown for paid media.","ar":"كتابة سيناريو، وإنتاج سينمائي، ونسخة 60 ثانية للإعلانات المدفوعة."}'::jsonb, 'draft', 3)
on conflict (tenant_id, slug) do nothing;

-- team_members (30-legacy-demo.json)
insert into public.team_members (tenant_id, slug, name, bio, status, sort_order) values
  ('00000000-0000-0000-0000-0000000000b1', 'lead-creative', '{"en":"Creative Director","ar":"المدير الإبداعي"}'::jsonb, '{"en":"Leads brand and art direction across the studio.","ar":"يقود اتجاه العلامة والفن في الاستوديو."}'::jsonb, 'draft', 1),
  ('00000000-0000-0000-0000-0000000000b1', 'head-of-video', '{"en":"Head of Video","ar":"رئيس قسم الفيديو"}'::jsonb, '{"en":"Oversees film, motion, and post-production.","ar":"يشرف على الفيلم والموشن والمونتاج."}'::jsonb, 'draft', 2),
  ('00000000-0000-0000-0000-0000000000b1', 'head-of-growth', '{"en":"Head of Growth","ar":"رئيس قسم النمو"}'::jsonb, '{"en":"Runs SEO/GEO/AEO, social, and performance.","ar":"يدير تحسين محركات البحث ووسائل التواصل والأداء."}'::jsonb, 'draft', 3)
on conflict (tenant_id, slug) do nothing;

-- certifications (30-legacy-demo.json)
insert into public.certifications (tenant_id, slug, name, issuer, year, status, sort_order) values
  ('00000000-0000-0000-0000-0000000000b1', 'google-partner', '{"en":"Google Partner","ar":"شريك جوجل"}'::jsonb, '{"en":"Google","ar":"جوجل"}'::jsonb, 2025, 'draft', 1),
  ('00000000-0000-0000-0000-0000000000b1', 'meta-partner', '{"en":"Meta Business Partner","ar":"شريك أعمال ميتا"}'::jsonb, '{"en":"Meta","ar":"ميتا"}'::jsonb, 2025, 'draft', 2)
on conflict (tenant_id, slug) do nothing;

-- statistics (30-legacy-demo.json)
insert into public.statistics (tenant_id, slug, label, value, status, sort_order) values
  ('00000000-0000-0000-0000-0000000000b1', 'projects', '{"en":"Projects delivered","ar":"مشروع منجز"}'::jsonb, '150+', 'draft', 1),
  ('00000000-0000-0000-0000-0000000000b1', 'services', '{"en":"Creative services","ar":"خدمة إبداعية"}'::jsonb, '14', 'draft', 2),
  ('00000000-0000-0000-0000-0000000000b1', 'years', '{"en":"Years in MENA","ar":"سنوات في المنطقة"}'::jsonb, '8', 'draft', 3)
on conflict (tenant_id, slug) do nothing;

-- partner_logos (30-legacy-demo.json)
insert into public.partner_logos (tenant_id, name, logo_url, sort_order, visible)
  select '00000000-0000-0000-0000-0000000000b1', 'Riyadh Season', '/partners/riyadh-season.svg', 1, false
  where not exists (select 1 from public.partner_logos where tenant_id = '00000000-0000-0000-0000-0000000000b1' and name = 'Riyadh Season');
insert into public.partner_logos (tenant_id, name, logo_url, sort_order, visible)
  select '00000000-0000-0000-0000-0000000000b1', 'NEOM', '/partners/neom.svg', 2, false
  where not exists (select 1 from public.partner_logos where tenant_id = '00000000-0000-0000-0000-0000000000b1' and name = 'NEOM');
insert into public.partner_logos (tenant_id, name, logo_url, sort_order, visible)
  select '00000000-0000-0000-0000-0000000000b1', 'stc', '/partners/stc.svg', 3, false
  where not exists (select 1 from public.partner_logos where tenant_id = '00000000-0000-0000-0000-0000000000b1' and name = 'stc');
insert into public.partner_logos (tenant_id, name, logo_url, sort_order, visible)
  select '00000000-0000-0000-0000-0000000000b1', 'Saudi Arabian Airlines', '/partners/saudia.svg', 4, false
  where not exists (select 1 from public.partner_logos where tenant_id = '00000000-0000-0000-0000-0000000000b1' and name = 'Saudi Arabian Airlines');
insert into public.partner_logos (tenant_id, name, logo_url, sort_order, visible)
  select '00000000-0000-0000-0000-0000000000b1', 'Aramco', '/partners/aramco.svg', 5, false
  where not exists (select 1 from public.partner_logos where tenant_id = '00000000-0000-0000-0000-0000000000b1' and name = 'Aramco');
insert into public.partner_logos (tenant_id, name, logo_url, sort_order, visible)
  select '00000000-0000-0000-0000-0000000000b1', 'Qiddiya', '/partners/qiddiya.svg', 6, false
  where not exists (select 1 from public.partner_logos where tenant_id = '00000000-0000-0000-0000-0000000000b1' and name = 'Qiddiya');

-- categories (30-legacy-demo.json)
insert into public.categories (tenant_id, slug, name) values
  ('00000000-0000-0000-0000-0000000000b1', 'insights', '{"en":"Insights","ar":"رؤى"}'::jsonb)
on conflict (tenant_id, slug) do nothing;

-- blog_posts (30-legacy-demo.json)
insert into public.blog_posts (tenant_id, slug, title, excerpt, body_html, author_id, category_id, status, published_at, reading_minutes) values
  ('00000000-0000-0000-0000-0000000000b1', 'arabic-first-brand-systems', '{"en":"Arabic-first brand systems","ar":"أنظمة هوية تبدأ بالعربية"}'::jsonb, '{"en":"Why designing the Arabic wordmark first makes the Latin one better.","ar":"لماذا يبدأ تصميم الشعار بالعربية أولًا يحسّن النسخة اللاتينية."}'::jsonb, '{"en":"<p>Designing Arabic-first forces clarity in the letterforms that Latin then inherits.</p>","ar":"<p>التصميم بالعربية أولًا يفرض وضوحًا في الأحرف ترثه اللاتينية لاحقًا.</p>"}'::jsonb, (select id from public.team_members where tenant_id = '00000000-0000-0000-0000-0000000000b1' and slug = 'lead-creative'), (select id from public.categories where tenant_id = '00000000-0000-0000-0000-0000000000b1' and slug = 'insights'), 'draft', '2026-06-10T09:00:00Z', 4),
  ('00000000-0000-0000-0000-0000000000b1', 'getting-cited-by-ai-answer-engines', '{"en":"Getting cited by AI answer engines","ar":"أن تُذكر في محركات الإجابة بالذكاء الاصطناعي"}'::jsonb, '{"en":"Answer-first structure, named stats, and real authorship win citations.","ar":"البنية القائمة على الإجابة، والإحصاءات المسماة، والتأليف الحقيقي تكسب الاستشهادات."}'::jsonb, '{"en":"<p>Answer-engine visibility rewards answer-first paragraphs and named, verifiable authors.</p>","ar":"<p>ظهورك في محركات الإجابة يكافئ الفقرات التي تبدأ بالإجابة والمؤلفين المعروفين الموثوقين.</p>"}'::jsonb, (select id from public.team_members where tenant_id = '00000000-0000-0000-0000-0000000000b1' and slug = 'head-of-growth'), (select id from public.categories where tenant_id = '00000000-0000-0000-0000-0000000000b1' and slug = 'insights'), 'draft', '2026-06-14T09:00:00Z', 5)
on conflict (tenant_id, slug) do nothing;

commit;
