// Every case in tests/authz/cases, as "<module>: <case name>", sorted. Pinned on purpose:
// tests/authz/endpointCoverage.spec.ts fails when a module or a row goes missing (a merge
// that drops a file, a resolution that keeps one side) and when one appears that is not
// listed. A change that adds, renames or removes a case edits its line here in the same
// commit; one line per case, in sorted order, so parallel changes rarely meet.

export const CASE_MANIFEST: readonly string[] = [
  'analytics: analytics dashboards',
  'analytics: search analytics',
  'appearance: navigation create',
  'appearance: navigation delete',
  'appearance: navigation list',
  'appearance: navigation read one',
  'appearance: navigation reorder',
  'appearance: navigation update',
  'appearance: theme delete',
  'appearance: theme list',
  'appearance: theme read one',
  'appearance: theme update',
  'appearance: theme write',
  'applications: application CV download',
  'applications: application contact details (pii)',
  'applications: application detail',
  'applications: application erase',
  'applications: application status / notes',
  'applications: applications list',
  'audit: audit log read',
  'backups: backup export',
  'blog: blog create',
  'blog: blog delete',
  'blog: blog list',
  'blog: blog read one',
  'blog: blog update',
  'blog: categories create',
  'blog: categories delete',
  'blog: categories list',
  'blog: categories read one',
  'blog: categories update',
  'collections: certifications create',
  'collections: certifications delete',
  'collections: certifications list',
  'collections: certifications read one',
  'collections: certifications reorder',
  'collections: certifications update',
  'collections: clients clear for disclosure (visible = publish)',
  'collections: clients create',
  'collections: clients delete',
  'collections: clients list',
  'collections: clients read one',
  'collections: clients reorder',
  'collections: statistics create (count-up value)',
  'collections: statistics delete',
  'collections: statistics list',
  'collections: statistics read one',
  'collections: statistics reorder',
  'collections: statistics update',
  'collections: team create (leadership fields)',
  'collections: team delete',
  'collections: team list',
  'collections: team read one',
  'collections: team reorder',
  'collections: team update',
  'collections: testimonials create',
  'collections: testimonials delete',
  'collections: testimonials list',
  'collections: testimonials publish',
  'collections: testimonials read one',
  'collections: testimonials reorder',
  'crm: CRM people (assignees)',
  'crm: CRM stages',
  'dashboard: dashboard',
  'health: site health',
  'health: system logs clear',
  'health: system logs read',
  'integrations: integrations read',
  'integrations: integrations write',
  'leads: lead CSV export',
  'leads: lead KPIs',
  'leads: lead contact reveal',
  'leads: lead detail',
  'leads: lead internal notes (legacy panel, leads.pii)',
  'leads: lead notes thread (add)',
  'leads: lead notes thread (read)',
  'leads: lead pipeline board',
  'leads: lead query (CRM list)',
  'leads: lead status (legacy panel)',
  'leads: lead timeline',
  'leads: leads list',
  'leadsWrite: lead added by hand (leads.manage + leads.pii)',
  'leadsWrite: lead erase (crm.erase, Admin only)',
  'leadsWrite: lead marks (star, read, log contact)',
  'leadsWrite: lead note delete (crm.erase, Admin only)',
  'leadsWrite: lead pipeline change (versioned PATCH)',
  'leadsWrite: leads bulk change',
  'media: media hard delete (media.hardDelete — Admin only)',
  'media: media list',
  'media: media metadata (SEO "meta only" path)',
  'media: media read one',
  'media: media register (external asset)',
  'media: media update (full row)',
  'media: media usage',
  'pages: page visibility toggle',
  'pages: pages create',
  'pages: pages delete',
  'pages: pages list',
  'pages: pages read one',
  'pages: pages update',
  'pages: sections create',
  'pages: sections delete',
  'pages: sections list',
  'pages: sections read one',
  'pages: sections reorder',
  'pages: sections update',
  'portfolio: portfolio create (save_portfolio)',
  'portfolio: portfolio delete',
  'portfolio: portfolio list',
  'portfolio: portfolio publish',
  'portfolio: portfolio read one',
  'portfolio: portfolio reorder',
  'portfolio: portfolio services-only update (child set)',
  'portfolio: sectors create',
  'portfolio: sectors delete',
  'portfolio: sectors list',
  'portfolio: sectors read one',
  'portfolio: sectors reorder',
  'portfolio: sectors update',
  'search: admin search (the command palette)',
  'seo: entity SEO read',
  'seo: entity SEO write',
  'seo: global SEO defaults read',
  'seo: global SEO defaults write',
  'seo: redirects create',
  'seo: redirects delete (SEO may — not the content default)',
  'seo: redirects edge status',
  'seo: redirects list',
  'seo: redirects read one',
  'seo: redirects sync to edge',
  'seo: redirects update',
  'services: disciplines archive (Admin-only — hides every service under it)',
  'services: disciplines create',
  'services: disciplines delete',
  'services: disciplines list',
  'services: disciplines publish (status transition)',
  'services: disciplines read one',
  'services: disciplines reorder',
  'services: service cases archive (Admin-only transition)',
  'services: service cases create',
  'services: service cases delete',
  'services: service cases list',
  'services: service cases publish',
  'services: service cases read one',
  'services: services archive (Admin-only transition)',
  'services: services create',
  'services: services delete',
  'services: services list',
  'services: services publish (status transition)',
  'services: services read one',
  'services: services reorder',
  'settings: general settings read',
  'settings: general settings write',
  'settings: maintenance read',
  'settings: maintenance toggle',
  'settings: site profile opens job applications (Admin-only)',
  'settings: site profile read',
  'settings: site profile write',
  'settings: site profile write, applications flag unchanged',
  'styleFinder: style-finder logic config',
  'styleFinder: style-finder logic config read',
  'styleFinder: style-finder question create',
  'styleFinder: style-finder question delete',
  'styleFinder: style-finder question read one',
  'styleFinder: style-finder question update',
  'styleFinder: style-finder questions list',
  'styleFinder: style-finder questions reorder',
  'styleFinder: style-finder style create',
  'styleFinder: style-finder style delete',
  'styleFinder: style-finder style read one',
  'styleFinder: style-finder style update',
  'styleFinder: style-finder styles list',
  'styleFinder: style-finder styles reorder',
  'users: user invite',
  'users: user list',
  'users: user update',
];
