import {
  bilingualList,
  NOT_ARCHIVED,
  PLACEHOLDER_FIELD,
  SCHEDULED_FIELD,
  SORT_FIELD,
  STATUS_FIELD,
} from './fields';
import type { ResourceUi } from './types';

// Our Work: the list and the form at /admin/portfolio.
export const portfolioUi: ResourceUi = {
  slug: 'portfolio',
  title: 'Our Work',
  singular: 'Case study',
  hasStatus: true,
  reorder: true,
  columns: [
    { key: 'title', label: 'Title', kind: 'bilingual' },
    { key: 'project_type', label: 'Type', kind: 'bilingual' },
    { key: 'year', label: 'Year' },
    { key: 'is_featured', label: 'Featured', kind: 'boolean' },
    { key: 'is_placeholder', label: 'Placeholder', kind: 'boolean' },
    { key: 'status', label: 'Status', kind: 'status' },
    { key: 'updated_at', label: 'Updated', kind: 'date' },
  ],
  fields: [
    {
      name: 'slug',
      label: 'Slug',
      kind: 'slug',
      required: true,
      help: 'The case study’s address: /portfolio/<slug>. “all” is reserved.',
    },
    { name: 'title', label: 'Project name', kind: 'bilingual', required: true },
    {
      name: 'projectType',
      label: 'Project type',
      kind: 'bilingual',
      nullable: true,
      help: 'Shown on the card and in the title band — “Brand film”, “Rebrand”. Required to publish.',
    },
    {
      name: 'teaser',
      label: 'Card blurb',
      kind: 'bilingual',
      nullable: true,
      help: 'One line under the project on Our Work and All projects. Empty = the overview.',
    },
    {
      name: 'sectorId',
      label: 'Industry',
      kind: 'relation',
      relation: { resource: 'sectors', labelKey: 'name' },
    },
    {
      name: 'clientId',
      label: 'Client',
      kind: 'relation',
      relation: { resource: 'clients', labelKey: 'name' },
      help: 'A client not yet cleared for disclosure (not visible) shows as “Confidential client”.',
    },
    { name: 'year', label: 'Year', kind: 'number' },
    {
      name: 'serviceIds',
      label: 'Services',
      kind: 'multiRelation',
      relation: { resource: 'services', labelKey: 'title', filter: NOT_ARCHIVED },
      maxItems: 20,
      help: 'In the order the case study lists them; they are also its catalogue filters. Archived services are not offered; one already listed stays until you remove it.',
    },
    {
      name: 'isFeatured',
      label: 'Featured',
      kind: 'checkbox',
      help: 'Featured projects lead Our Work and Selected work on the home page.',
    },
    {
      name: 'posterMediaId',
      label: 'Poster',
      kind: 'media',
      help: 'The card image. Needs alt text in English and Arabic to publish.',
    },
    {
      name: 'preview',
      label: 'Card hover clip',
      kind: 'clip',
      help: 'A short window of a video, played while the card is hovered (never on touch).',
    },
    {
      name: 'lead',
      label: 'Lead',
      kind: 'bilingual',
      nullable: true,
      help: 'The case study’s opening line.',
    },
    { name: 'summary', label: 'Overview', kind: 'prose' },
    { name: 'goal', label: 'The goal', kind: 'bilingual', nullable: true },
    { name: 'result', label: 'The result', kind: 'bilingual', nullable: true },
    bilingualList('scope', 'Scope', 10, 'What the studio did, one line each.'),
    bilingualList('keywords', 'Keywords', 6, 'The chips under the title.'),
    {
      name: 'results',
      label: 'Result cards',
      kind: 'repeater',
      maxItems: 4,
      help: 'Figures only when they are real — a placeholder figure (XX) cannot be published.',
      itemFields: [
        { name: 'value', label: 'Figure', kind: 'text', required: true, help: 'e.g. 3.2M, +40%' },
        { name: 'label', label: 'What it measures', kind: 'bilingual', required: true },
      ],
    },
    {
      name: 'media',
      label: 'Case-study media',
      kind: 'repeater',
      maxItems: 40,
      help: 'One hero and one final film at most; breakdown items need their kind. Saved with the case study in one step.',
      itemFields: [
        {
          name: 'role',
          label: 'Where it appears',
          kind: 'select',
          required: true,
          options: [
            { value: 'hero', label: 'Hero banner' },
            { value: 'final', label: 'Final film' },
            { value: 'breakdown', label: 'Breakdown' },
            { value: 'gallery', label: 'Gallery' },
          ],
        },
        {
          name: 'kind',
          label: 'Kind',
          kind: 'select',
          required: true,
          options: [
            { value: 'image', label: 'Image' },
            { value: 'video', label: 'Video' },
          ],
        },
        { name: 'mediaId', label: 'Image (a video’s poster)', kind: 'media' },
        { name: 'clip', label: 'Video', kind: 'clip' },
        { name: 'durationLabel', label: 'Duration shown (m:ss)', kind: 'text' },
        { name: 'caption', label: 'Caption', kind: 'bilingual' },
        {
          name: 'breakdownKind',
          label: 'Breakdown kind',
          kind: 'select',
          options: [
            { value: 'sketch', label: 'Sketch' },
            { value: 'bts', label: 'Behind the scenes' },
            { value: 'process', label: 'Process' },
          ],
        },
        {
          name: 'layout',
          label: 'Layout',
          kind: 'select',
          options: [
            { value: 'half', label: 'Half width' },
            { value: 'wide', label: 'Wide' },
            { value: 'third', label: 'One third' },
          ],
        },
      ],
    },
    { name: 'body', label: 'Body', kind: 'richtext' },
    {
      name: 'nextPortfolioId',
      label: 'Next project',
      kind: 'relation',
      relation: { resource: 'portfolio', labelKey: 'title' },
      help: 'Empty = the next project in catalogue order.',
    },
    PLACEHOLDER_FIELD,
    SORT_FIELD,
    STATUS_FIELD,
    SCHEDULED_FIELD,
  ],
};
