/// <reference path="../.astro/types.d.ts" />
/// <reference path="../worker-configuration.d.ts" />

// `Env` and the `cloudflare:workers` module are generated by `npx wrangler types` into
// worker-configuration.d.ts, straight from the wrangler.jsonc bindings — one source of
// truth, no hand-maintained binding list to drift. Re-run `npm run cf:types` after
// editing wrangler.jsonc.
type CloudflareEnv = Env;

declare namespace App {
  interface Locals {
    // Adapter v14: the ONLY runtime property is `cfContext`. There is deliberately NO
    // `runtime` declared here — `locals.runtime.env` is a getter that THROWS ("removed in
    // Astro v6"). Declaring it makes TypeScript bless code that 500s on every request,
    // which is exactly how that defect passed check + tsc + build during this migration.
    cfContext: ExecutionContext;
    // Per-request CSP nonce (set in src/middleware.ts; consumed by <SeoHead>).
    cspNonce: string;
    // Resolved auth context (null for anonymous public requests).
    session: import('@/lib/auth/types').AuthContext | null;
  }
}
