// The admin icon names: every <symbol> in public/styles/admin-icons.svg, the client's
// prototype set (Admin v2 F1). tests/lib/adminIcons.spec.ts keeps this list and the
// sprite identical, so an icon a component asks for always exists.
export const ICON_NAMES = [
  'home',
  'pages',
  'layers',
  'briefcase',
  'quote',
  'users',
  'image',
  'inbox',
  'chart',
  'palette',
  'header',
  'settings',
  'search',
  'bell',
  'plus',
  'x',
  'check',
  'trash',
  'edit',
  'eye',
  'eyeoff',
  'drag',
  'arrow',
  'back',
  'ext',
  'copy',
  'more',
  'play',
  'video',
  'globe',
  'mail',
  'phone',
  'whatsapp',
  'desktop',
  'tablet',
  'mobile',
  'refresh',
  'save',
  'upload',
  'download',
  'filter',
  'star',
  'sparkle',
  'clock',
  'info',
  'warn',
  'lock',
  'shield',
  'loader',
  'type',
  'link',
  'grid',
  'list',
  'kanban',
  'logout',
  'key',
  'history',
  'db',
  'tag',
  'sun',
  'move',
  'send',
  'note',
  'cursor',
  'form',
  'seo',
  'plug',
  'chevron',
  'chevd',
  'paint',
  'cal',
  'film',
  'code',
  'pin',
  'logo',
  'zap',
  'hand',
] as const;

export type IconName = (typeof ICON_NAMES)[number];

/** The sprite's URL; one cached same-origin request serves every icon. */
export const ICON_SPRITE = '/styles/admin-icons.svg';
