import type { LocalizedDoc } from '@schemas/tiptap';
import type { ContentStatus } from '@schemas/primitives';
import {
  AiQuestionUpdateSchema,
  AiQuestionWriteSchema,
  AiStyleUpdateSchema,
  AiStyleWriteSchema,
  CategoryUpdateSchema,
  CategoryWriteSchema,
  CertificationUpdateSchema,
  CertificationWriteSchema,
  ClientUpdateSchema,
  ClientWriteSchema,
  MediaUpdateSchema,
  MediaWriteSchema,
  NavItemUpdateSchema,
  NavItemWriteSchema,
  PageUpdateSchema,
  PageWriteSchema,
  PortfolioUpdateSchema,
  PortfolioWriteSchema,
  PostUpdateSchema,
  PostWriteSchema,
  RedirectUpdateSchema,
  RedirectWriteSchema,
  SectorUpdateSchema,
  SectorWriteSchema,
  SectionUpdateSchema,
  SectionWriteSchema,
  ServiceUpdateSchema,
  ServiceWriteSchema,
  StatisticUpdateSchema,
  StatisticWriteSchema,
  TeamMemberUpdateSchema,
  TeamMemberWriteSchema,
  TestimonialUpdateSchema,
  TestimonialWriteSchema,
  ThemeUpdateSchema,
  ThemeWriteSchema,
  type PortfolioMediaItem,
} from '@schemas/admin';
import type { VideoClip } from '@schemas/media';
import { sectionContentIssues, type SectionType } from '@schemas/sections';
import { isStaticMediaKey, staticImage } from '@/lib/media/static';
import { renderTiptapToHtml, readingMinutes, sanitizeHref } from '@/lib/content/tiptap';
import { NotFoundError, OptimisticLockError, ValidationError } from './errors';
import { getRow, translateWriteError, type ConstraintFields } from './crud';
import type { ResourceConfig, ResourcePayload } from './resource';

// One config per CRUD entity. Everything structural (tenant scoping, authz, audit,
// optimistic locking) lives in resource.ts; this file is only "which table, which
// columns, which capability, how does the wire shape map to columns".

type Input = ResourcePayload;

/**
 * camelCase input → snake_case column patch.
 *
 * This is the allowlist that makes mass-assignment impossible: a client can send
 * `{"tenant_id": "<someone else's>"}` or `{"version": 999}` all it likes, because only
 * keys named in `map` are ever copied into the object handed to the query builder.
 * `undefined` is skipped so a PATCH touches exactly the fields it sent — `null` is
 * kept, because "clear this field" is a real edit.
 */
function pick(input: Input, map: Record<string, string>): Input {
  const out: Input = {};
  for (const [key, column] of Object.entries(map)) {
    if (key in input && input[key] !== undefined) out[column] = input[key];
  }
  return out;
}

/** Locale-keyed Tiptap JSON → locale-keyed sanitised HTML (the render-time cache). */
function deriveBodyHtml(body: unknown): Record<string, string> | null {
  if (!body || typeof body !== 'object') return null;
  const doc = body as Partial<LocalizedDoc>;
  const out: Record<string, string> = {};
  if (doc.en) out['en'] = renderTiptapToHtml(doc.en);
  if (doc.ar) out['ar'] = renderTiptapToHtml(doc.ar);
  return out;
}

/**
 * Adds the derived HTML cache alongside the stored JSON.
 *
 * Both are written in the same statement on purpose. If `body_html` were regenerated
 * lazily at render time, the public Tier-A page would be re-sanitising on every cache
 * miss (a per-request cost on the latency-critical path), and if it were regenerated by
 * a separate call the two could drift — leaving stored JSON that says one thing and
 * cached HTML that says another, with the HTML being what visitors actually see.
 */
function withBodyHtml(values: Input, input: Input): Input {
  if (!('body' in input) || input['body'] === undefined) return values;
  return { ...values, body_html: deriveBodyHtml(input['body']) };
}

const statusOf = (input: Input): ContentStatus | undefined =>
  typeof input['status'] === 'string' ? (input['status'] as ContentStatus) : undefined;

/**
 * A save with status `published` carries a publish date; the kernel drops it again when the
 * row already has one (resource.ts PATCH), so the FIRST publish date is never rewritten
 * (truthful dates, Pillar 3).
 */
function publishStamp(values: Input): Input {
  return values['status'] === 'published'
    ? { ...values, published_at: new Date().toISOString() }
    : values;
}

function requireBilingual(row: Input, column: string, label: string): void {
  const value = row[column];
  const record = (value ?? {}) as Record<string, unknown>;
  if (!record['en'] || !record['ar']) {
    throw new ValidationError(`${label} must have both English and Arabic before publishing`);
  }
}

/**
 * The app half of the placeholder rule (0025 is the database half, production only):
 * design-delivery samples never go live through the admin, in any environment — seeded
 * staging rows are published by the seed, not by an editor.
 */
function refusePlaceholder(row: Input, what: string): void {
  if (row['is_placeholder'] === true) {
    throw new ValidationError(
      `this ${what} is placeholder content — replace it and untick “Placeholder” before it goes live`,
      'isPlaceholder',
    );
  }
}

/** A clip's wire shape → its four columns (`null` clears all four). */
function clipColumns(clip: VideoClip | null, prefix: string, video: string): Input {
  return {
    [`${prefix}${video}_uid`]: clip?.streamUid ?? null,
    [`${prefix}${video}_path`]: clip?.path ?? null,
    [`${prefix}start_s`]: clip?.startS ?? null,
    [`${prefix}end_s`]: clip?.endS ?? null,
  };
}

/** Four clip columns → the wire shape, or null when there is no source. */
function clipOfColumns(
  uid: unknown,
  path: unknown,
  start: unknown,
  end: unknown,
): Record<string, unknown> | null {
  if (!uid && !path) return null;
  const clip: Record<string, unknown> = {};
  if (uid) clip['streamUid'] = uid;
  if (path) clip['path'] = path;
  if (start !== null && start !== undefined) clip['startS'] = Number(start);
  if (end !== null && end !== undefined) clip['endS'] = Number(end);
  return clip;
}

const bySortOrder = (a: Input, b: Input) => Number(a['sort_order']) - Number(b['sort_order']);

// ── Services ────────────────────────────────────────────────────────────────────

export const serviceResource: ResourceConfig = {
  table: 'services',
  entity: 'service',
  writeCap: 'services.write',
  // SEO can list/read a service to author its meta, but not write the row itself.
  readCaps: ['services.write', 'seo.entityMeta'],
  listColumns: 'id,slug,title,status,is_teaser,sort_order,version,updated_at',
  columns:
    'id,slug,title,short_title,blurb,body,body_html,hero_video_uid,category,status,is_teaser,sort_order,version,published_at,scheduled_for,created_at,updated_at',
  orderBy: { column: 'sort_order', ascending: true },
  searchColumn: 'slug',
  createSchema: ServiceWriteSchema,
  updateSchema: ServiceUpdateSchema,
  toRow: (input) =>
    publishStamp(
      withBodyHtml(
        pick(input as Input, {
          slug: 'slug',
          title: 'title',
          blurb: 'blurb',
          body: 'body',
          heroVideoUid: 'hero_video_uid',
          category: 'category',
          shortTitle: 'short_title',
          status: 'status',
          isTeaser: 'is_teaser',
          sortOrder: 'sort_order',
          scheduledFor: 'scheduled_for',
        }),
        input as Input,
      ),
    ),
  statusOf: (input) => statusOf(input as Input),
  assertPublishable: (row) => requireBilingual(row, 'title', 'Service title'),
};

// ── Blog ────────────────────────────────────────────────────────────────────────

export const postResource: ResourceConfig = {
  table: 'blog_posts',
  entity: 'blog_post',
  writeCap: 'blog.write',
  readCaps: ['blog.write', 'seo.entityMeta'],
  listColumns: 'id,slug,title,status,published_at,scheduled_for,version,updated_at',
  columns:
    'id,slug,title,excerpt,body,body_html,author_id,category_id,cover_image_url,status,published_at,scheduled_for,reading_minutes,version,created_at,updated_at',
  orderBy: { column: 'updated_at', ascending: false },
  searchColumn: 'slug',
  filterableColumns: ['category_id', 'author_id'],
  createSchema: PostWriteSchema,
  updateSchema: PostUpdateSchema,
  toRow: (input) => {
    const values = publishStamp(
      withBodyHtml(
        pick(input as Input, {
          slug: 'slug',
          title: 'title',
          excerpt: 'excerpt',
          body: 'body',
          authorId: 'author_id',
          categoryId: 'category_id',
          coverImageUrl: 'cover_image_url',
          status: 'status',
          scheduledFor: 'scheduled_for',
        }),
        input as Input,
      ),
    );
    const body = (input as Input)['body'] as Partial<LocalizedDoc> | undefined;
    // Reading time is DERIVED, never authored: an editor-supplied number drifts from
    // the body the moment anyone edits it, and it is user-visible.
    return body?.en ? { ...values, reading_minutes: readingMinutes(body.en) } : values;
  },
  statusOf: (input) => statusOf(input as Input),
  assertPublishable: (row) => {
    requireBilingual(row, 'title', 'Post title');
    // CLAUDE.md Pillar 3: "E-E-A-T author pages — no anonymous authorship". A published
    // post with a null author is the exact thing that rule forbids, so it is refused
    // here rather than being allowed to reach the JSON-LD builder and emit an Article
    // with no `author`.
    if (!row['author_id']) {
      throw new ValidationError('a published post must have an author (E-E-A-T)', 'authorId');
    }
  },
};

// ── Portfolio ───────────────────────────────────────────────────────────────────

/** A media item as the form edits it (camelCase) → one element of save_portfolio's p_media. */
function mediaItemToRow(item: PortfolioMediaItem): Input {
  const clip = item.clip ?? null;
  return {
    role: item.role,
    kind: item.kind,
    media_id: item.mediaId ?? null,
    video_uid: clip?.streamUid ?? null,
    video_path: clip?.path ?? null,
    clip_start_s: clip?.startS ?? null,
    clip_end_s: clip?.endS ?? null,
    duration_label: item.durationLabel ?? null,
    caption: item.caption ?? null,
    breakdown_kind: item.breakdownKind ?? null,
    layout: item.layout ?? null,
  };
}

/** A stored portfolio_media row → the form's item. */
function mediaRowToItem(row: Input): Input {
  const item: Input = { role: row['role'], kind: row['kind'] };
  if (row['media_id']) item['mediaId'] = row['media_id'];
  const clip = clipOfColumns(
    row['video_uid'],
    row['video_path'],
    row['clip_start_s'],
    row['clip_end_s'],
  );
  if (clip) item['clip'] = clip;
  if (row['duration_label']) item['durationLabel'] = row['duration_label'];
  if (row['caption']) item['caption'] = row['caption'];
  if (row['breakdown_kind']) item['breakdownKind'] = row['breakdown_kind'];
  if (row['layout']) item['layout'] = row['layout'];
  return item;
}

const PORTFOLIO_CONSTRAINTS: ConstraintFields = {
  portfolio_tenant_id_slug_key: {
    field: 'slug',
    message: 'another case study already uses this slug',
  },
  portfolio_slug_not_reserved: {
    field: 'slug',
    message: '“all” is reserved for the All projects page',
  },
  portfolio_preview_window: {
    field: 'preview',
    message: 'the hover clip needs a start and an end, at most 30 seconds apart',
  },
  portfolio_next_not_self: {
    field: 'nextPortfolioId',
    message: 'a case study cannot be its own next project',
  },
  portfolio_media_one_hero: { field: 'media', message: 'a case study has one hero item at most' },
  portfolio_media_one_final: { field: 'media', message: 'a case study has one final film at most' },
  portfolio_services_pkey: { field: 'serviceIds', message: 'a service is listed twice' },
  portfolio_media_breakdown_kind: {
    field: 'media',
    message: 'a breakdown item needs its kind (sketch / BTS / process); other items none',
  },
};

export const portfolioResource: ResourceConfig = {
  table: 'portfolio',
  entity: 'portfolio',
  writeCap: 'portfolio.write',
  readCaps: ['portfolio.write', 'seo.entityMeta'],
  listColumns:
    'id,slug,title,project_type,year,is_featured,is_placeholder,status,sort_order,version,updated_at',
  // The child sets ride along as embeds so the form loads them with the row; fromRow
  // turns them into `service_ids` / `media` in the order the editor gave.
  columns:
    'id,slug,title,summary,body,body_html,status,sort_order,version,published_at,scheduled_for,' +
    'created_at,updated_at,project_type,teaser,lead,goal,result,scope,keywords,results,' +
    'sector_id,client_id,year,is_featured,poster_media_id,preview_video_uid,preview_video_path,' +
    'preview_start_s,preview_end_s,next_portfolio_id,is_placeholder,' +
    'portfolio_services(service_id,sort_order),' +
    'portfolio_media(role,kind,media_id,video_uid,video_path,clip_start_s,clip_end_s,' +
    'duration_label,caption,breakdown_kind,layout,sort_order)',
  orderBy: { column: 'sort_order', ascending: true },
  searchColumn: 'slug',
  filterableColumns: ['is_featured', 'sector_id', 'client_id'],
  createSchema: PortfolioWriteSchema,
  updateSchema: PortfolioUpdateSchema,
  constraintFields: PORTFOLIO_CONSTRAINTS,
  toRow: (input) => {
    const values = publishStamp(
      withBodyHtml(
        pick(input as Input, {
          slug: 'slug',
          title: 'title',
          summary: 'summary',
          body: 'body',
          status: 'status',
          sortOrder: 'sort_order',
          scheduledFor: 'scheduled_for',
          projectType: 'project_type',
          teaser: 'teaser',
          lead: 'lead',
          goal: 'goal',
          result: 'result',
          scope: 'scope',
          keywords: 'keywords',
          results: 'results',
          sectorId: 'sector_id',
          clientId: 'client_id',
          year: 'year',
          isFeatured: 'is_featured',
          posterMediaId: 'poster_media_id',
          nextPortfolioId: 'next_portfolio_id',
          isPlaceholder: 'is_placeholder',
        }),
        input as Input,
      ),
    );
    const preview = (input as Input)['preview'];
    return preview === undefined
      ? values
      : { ...values, ...clipColumns((preview as VideoClip | null) ?? null, 'preview_', 'video') };
  },
  statusOf: (input) => statusOf(input as Input),
  // A case study and its services + media are ONE save (save_portfolio(), migration
  // 0022): SECURITY INVOKER so RLS applies to every row it writes, version-checked, and
  // every linked id fenced to the caller's tenant. The previous afterWrite replaced the
  // services in a second request — a failure there left a half-saved case study.
  childKeys: ['serviceIds', 'media'],
  persist: async ({ auth, sb, id, version, values, input }) => {
    const serviceIds = input['serviceIds'];
    const media = input['media'];
    const { data, error } = await sb.rpc('save_portfolio', {
      p_id: id,
      p_version: version,
      p_values: values,
      p_service_ids: Array.isArray(serviceIds) ? serviceIds : null,
      p_media: Array.isArray(media) ? (media as PortfolioMediaItem[]).map(mediaItemToRow) : null,
    });
    if (error) {
      if (error.code === '40001') throw new OptimisticLockError('portfolio');
      if (error.code === 'P0002') throw new NotFoundError('portfolio');
      throw translateWriteError(error, 'portfolio', 'write', PORTFOLIO_CONSTRAINTS);
    }
    const saved = (Array.isArray(data) ? data[0] : data) as { id?: string } | undefined;
    if (!saved?.id) throw new Error('save_portfolio returned no row');
    return getRow<Input>(sb, 'portfolio', auth, saved.id, portfolioResource.columns);
  },
  fromRow: (row) => {
    const { portfolio_services: links, portfolio_media: items, ...rest } = row;
    const out: Input = {
      ...rest,
      preview: clipOfColumns(
        row['preview_video_uid'],
        row['preview_video_path'],
        row['preview_start_s'],
        row['preview_end_s'],
      ),
    };
    if (Array.isArray(links)) {
      out['service_ids'] = [...(links as Input[])].sort(bySortOrder).map((l) => l['service_id']);
    }
    if (Array.isArray(items)) {
      out['media'] = [...(items as Input[])].sort(bySortOrder).map(mediaRowToItem);
    }
    return out;
  },
  // What a card and a case study need to be presentable — the public pages show these.
  assertPublishable: async (row, { auth, sb }) => {
    requireBilingual(row, 'title', 'Case study title');
    requireBilingual(row, 'project_type', 'Project type');
    refusePlaceholder(row, 'case study');
    const results = Array.isArray(row['results']) ? (row['results'] as Input[]) : [];
    if (results.some((r) => /X{2,}/i.test(String(r['value'] ?? '')))) {
      throw new ValidationError('a result card still shows a placeholder figure (XX)', 'results');
    }
    const posterId = row['poster_media_id'];
    if (!posterId)
      throw new ValidationError('choose a poster image before publishing', 'posterMediaId');
    const { data } = await sb
      .from('media_assets')
      .select('alt')
      .eq('tenant_id', auth.tenantId)
      .eq('id', String(posterId))
      .maybeSingle();
    const alt = (data?.['alt'] ?? {}) as Record<string, unknown>;
    if (!alt['en'] || !alt['ar']) {
      throw new ValidationError(
        'the poster needs alt text in English and Arabic before publishing',
        'posterMediaId',
      );
    }
  },
};

// ── Pages & sections ────────────────────────────────────────────────────────────

export const pageResource: ResourceConfig = {
  table: 'pages',
  entity: 'page',
  writeCap: 'pages.write',
  readCaps: ['pages.write', 'seo.entityMeta', 'maintenance.manage'],
  listColumns: 'id,slug,title,status,nav_visible,version,updated_at',
  columns:
    'id,slug,title,status,nav_visible,version,published_at,scheduled_for,created_at,updated_at',
  orderBy: { column: 'slug', ascending: true },
  searchColumn: 'slug',
  createSchema: PageWriteSchema,
  updateSchema: PageUpdateSchema,
  toRow: (input) =>
    publishStamp(
      pick(input as Input, {
        slug: 'slug',
        title: 'title',
        status: 'status',
        navVisible: 'nav_visible',
        scheduledFor: 'scheduled_for',
      }),
    ),
  statusOf: (input) => statusOf(input as Input),
  assertPublishable: (row) => requireBilingual(row, 'title', 'Page title'),
};

export const sectionResource: ResourceConfig = {
  table: 'page_sections',
  // A visible section on a published page is live copy, so turning `visible` on is gated
  // as a publish (content.publish). Every role that may edit sections holds it today; the
  // flag keeps the two capabilities from drifting apart unnoticed.
  publishFlag: 'visible',
  entity: 'page_section',
  writeCap: 'pages.write',
  listColumns: 'id,page_id,type,visible,sort_order,version,updated_at',
  columns:
    'id,page_id,type,content,visible,sort_order,is_placeholder,version,created_at,updated_at',
  orderBy: { column: 'sort_order', ascending: true },
  filterableColumns: ['page_id'],
  createSchema: SectionWriteSchema,
  updateSchema: SectionUpdateSchema,
  // `style` is deliberately absent: it is no longer writable (see SectionWriteSchema).
  toRow: (input) =>
    pick(input as Input, {
      pageId: 'page_id',
      type: 'type',
      content: 'content',
      visible: 'visible',
      sortOrder: 'sort_order',
      isPlaceholder: 'is_placeholder',
    }),
  // The schema validates content only when a payload carries BOTH type and content. A
  // PATCH of content alone (or of type alone) is checked here, against the type the row
  // will have — otherwise it saves "fine" and the loader silently drops it.
  assertWritable: (merged, { changed }) => {
    if (!('type' in changed) && !('content' in changed)) return;
    const [issue] = sectionContentIssues(merged['type'] as SectionType, merged['content'] ?? {});
    if (issue) {
      const where = issue.path.slice(1).join('.');
      throw new ValidationError(where ? `${where}: ${issue.message}` : issue.message, 'content');
    }
  },
};

// ── Taxonomy & about-page entities ──────────────────────────────────────────────

export const categoryResource: ResourceConfig = {
  table: 'categories',
  entity: 'category',
  writeCap: 'categories.manage',
  readCaps: ['categories.manage', 'blog.write', 'seo.entityMeta'],
  listColumns: 'id,slug,name,version',
  columns: 'id,slug,name,version,created_at,updated_at',
  orderBy: { column: 'slug', ascending: true },
  searchColumn: 'slug',
  createSchema: CategoryWriteSchema,
  updateSchema: CategoryUpdateSchema,
  toRow: (input) => pick(input as Input, { slug: 'slug', name: 'name' }),
};

export const teamResource: ResourceConfig = {
  table: 'team_members',
  entity: 'team_member',
  writeCap: 'blog.write',
  readCaps: ['blog.write', 'services.write', 'seo.entityMeta'],
  listColumns:
    'id,slug,name,role,is_leadership,is_placeholder,status,sort_order,version,updated_at',
  columns:
    'id,slug,name,bio,avatar_url,profile_user_id,role,linkedin_url,is_leadership,portrait_media_id,' +
    'is_placeholder,status,sort_order,version,created_at,updated_at',
  orderBy: { column: 'sort_order', ascending: true },
  searchColumn: 'slug',
  createSchema: TeamMemberWriteSchema,
  updateSchema: TeamMemberUpdateSchema,
  toRow: (input) =>
    pick(input as Input, {
      slug: 'slug',
      name: 'name',
      bio: 'bio',
      avatarUrl: 'avatar_url',
      profileUserId: 'profile_user_id',
      role: 'role',
      linkedinUrl: 'linkedin_url',
      isLeadership: 'is_leadership',
      portraitMediaId: 'portrait_media_id',
      isPlaceholder: 'is_placeholder',
      status: 'status',
      sortOrder: 'sort_order',
    }),
  statusOf: (input) => statusOf(input as Input),
  constraintFields: {
    team_members_linkedin_url_check: {
      field: 'linkedinUrl',
      message: 'a https://linkedin.com/in/… or /company/… address',
    },
  },
  assertPublishable: (row) => {
    requireBilingual(row, 'name', 'Name');
    refusePlaceholder(row, 'team member');
  },
};

export const certificationResource: ResourceConfig = {
  table: 'certifications',
  entity: 'certification',
  writeCap: 'services.write',
  listColumns: 'id,slug,name,year,status,sort_order,version,updated_at',
  columns: 'id,slug,name,issuer,year,logo_url,status,sort_order,version,created_at,updated_at',
  orderBy: { column: 'sort_order', ascending: true },
  searchColumn: 'slug',
  createSchema: CertificationWriteSchema,
  updateSchema: CertificationUpdateSchema,
  toRow: (input) =>
    pick(input as Input, {
      slug: 'slug',
      name: 'name',
      issuer: 'issuer',
      year: 'year',
      logoUrl: 'logo_url',
      status: 'status',
      sortOrder: 'sort_order',
    }),
  statusOf: (input) => statusOf(input as Input),
  assertPublishable: (row) => requireBilingual(row, 'name', 'Certification name'),
};

export const statisticResource: ResourceConfig = {
  table: 'statistics',
  entity: 'statistic',
  writeCap: 'services.write',
  listColumns: 'id,slug,label,value,placements,is_placeholder,status,sort_order,version,updated_at',
  columns:
    'id,slug,label,value,value_numeric,value_suffix,placements,placement_labels,is_placeholder,' +
    'status,sort_order,version,created_at,updated_at',
  orderBy: { column: 'sort_order', ascending: true },
  searchColumn: 'slug',
  createSchema: StatisticWriteSchema,
  updateSchema: StatisticUpdateSchema,
  toRow: (input) => {
    const i = input as Input;
    const values = pick(i, {
      slug: 'slug',
      label: 'label',
      value: 'value',
      valueNumeric: 'value_numeric',
      valueSuffix: 'value_suffix',
      placements: 'placements',
      placementLabels: 'placement_labels',
      isPlaceholder: 'is_placeholder',
      status: 'status',
      sortOrder: 'sort_order',
    });
    // The 0023 statistics_value_consistent CHECK: with a number, the displayed value IS the
    // number plus its suffix (derived here); free text written without a number drops the
    // count-up number, or the stored one would contradict it.
    const numeric = i['valueNumeric'];
    if (typeof numeric === 'number') {
      values['value'] = `${Number(numeric.toFixed(2))}${String(i['valueSuffix'] ?? '')}`;
    } else if (i['value'] !== undefined && i['value'] !== null && numeric === undefined) {
      values['value_numeric'] = null;
      values['value_suffix'] = null;
    }
    return values;
  },
  statusOf: (input) => statusOf(input as Input),
  // The form edits per-page labels as a list; the column is an object keyed by page.
  fromRow: (row) => {
    const labels = row['placement_labels'];
    if (!labels || typeof labels !== 'object' || Array.isArray(labels)) return row;
    return {
      ...row,
      placement_labels: Object.entries(labels as Record<string, unknown>).map(
        ([placement, label]) => ({ placement, label }),
      ),
    };
  },
  constraintFields: {
    statistics_value_consistent: {
      field: 'value',
      message: 'the value must read as the number plus its suffix',
    },
  },
  assertPublishable: (row) => {
    requireBilingual(row, 'label', 'Statistic label');
    refusePlaceholder(row, 'statistic');
  },
};

// ── Sectors · clients · testimonials (UI v2, migration 0021) ────────────────────

export const sectorResource: ResourceConfig = {
  table: 'sectors',
  entity: 'sector',
  // A taxonomy, like categories (§5 "Categories management": Admin + Content Creator).
  writeCap: 'categories.manage',
  // seo.entityMeta: SEO reviews a case study (portfolio readCaps) and its Industry picker
  // loads from here. RLS already admits every staff role (sectors_read).
  readCaps: ['categories.manage', 'portfolio.write', 'seo.entityMeta'],
  listColumns: 'id,slug,name,visible,sort_order,version,updated_at',
  columns: 'id,slug,name,visible,sort_order,version,created_at,updated_at',
  orderBy: { column: 'sort_order', ascending: true },
  searchColumn: 'slug',
  createSchema: SectorWriteSchema,
  updateSchema: SectorUpdateSchema,
  toRow: (input) =>
    pick(input as Input, {
      slug: 'slug',
      name: 'name',
      visible: 'visible',
      sortOrder: 'sort_order',
    }),
  constraintFields: {
    sectors_slug_check: {
      field: 'slug',
      message: 'lowercase letters, digits and hyphens, at most 64',
    },
    sectors_tenant_id_slug_key: { field: 'slug', message: 'another sector already uses this slug' },
  },
};

export const clientResource: ResourceConfig = {
  table: 'clients',
  entity: 'client',
  writeCap: 'portfolio.write',
  // Read by SEO too: the case-study editor's Client picker (RLS: clients_read, staff).
  readCaps: ['portfolio.write', 'seo.entityMeta'],
  // `visible` IS the public-disclosure permission: turning it on names a client on the
  // site, so it is gated like a publish (content.publish + the rules below).
  publishFlag: 'visible',
  constraintFields: {
    clients_slug_check: {
      field: 'slug',
      message: 'lowercase letters, digits and hyphens, at most 64',
    },
    clients_tenant_id_slug_key: { field: 'slug', message: 'another client already uses this slug' },
    clients_website_url_check: {
      field: 'websiteUrl',
      message: 'an https:// address, at most 300 characters',
    },
  },
  listColumns: 'id,slug,name,show_in_marquee,visible,is_placeholder,sort_order,version,updated_at',
  columns:
    'id,slug,name,logo_media_id,website_url,show_in_marquee,visible,is_placeholder,sort_order,' +
    'version,created_at,updated_at',
  orderBy: { column: 'sort_order', ascending: true },
  searchColumn: 'slug',
  filterableColumns: ['show_in_marquee', 'visible'],
  createSchema: ClientWriteSchema,
  updateSchema: ClientUpdateSchema,
  toRow: (input) =>
    pick(input as Input, {
      slug: 'slug',
      name: 'name',
      logoMediaId: 'logo_media_id',
      websiteUrl: 'website_url',
      showInMarquee: 'show_in_marquee',
      visible: 'visible',
      isPlaceholder: 'is_placeholder',
      sortOrder: 'sort_order',
    }),
  assertPublishable: (row) => {
    requireBilingual(row, 'name', 'Client name');
    refusePlaceholder(row, 'client');
  },
};

export const testimonialResource: ResourceConfig = {
  table: 'testimonials',
  entity: 'testimonial',
  writeCap: 'portfolio.write',
  listColumns:
    'id,slug,author_name,placements,portfolio_id,is_placeholder,status,sort_order,version,updated_at',
  columns:
    'id,slug,quote,author_name,author_role,client_id,portfolio_id,avatar_media_id,placements,' +
    'consent_obtained_at,consent_reference,is_placeholder,status,sort_order,version,' +
    'published_at,scheduled_for,created_at,updated_at',
  orderBy: { column: 'sort_order', ascending: true },
  searchColumn: 'slug',
  filterableColumns: ['portfolio_id'],
  createSchema: TestimonialWriteSchema,
  updateSchema: TestimonialUpdateSchema,
  constraintFields: {
    testimonials_consent_gate: {
      field: 'consentObtainedAt',
      message: 'record when consent was obtained before publishing or scheduling a quote',
    },
    testimonials_one_per_project: {
      field: 'portfolioId',
      message: 'that case study already has a published or scheduled quote',
    },
    testimonials_slug_check: {
      field: 'slug',
      message: 'lowercase letters, digits and hyphens, at most 64',
    },
    testimonials_tenant_id_slug_key: {
      field: 'slug',
      message: 'another quote already uses this slug',
    },
  },
  toRow: (input) =>
    publishStamp(
      pick(input as Input, {
        slug: 'slug',
        quote: 'quote',
        authorName: 'author_name',
        authorRole: 'author_role',
        clientId: 'client_id',
        portfolioId: 'portfolio_id',
        avatarMediaId: 'avatar_media_id',
        placements: 'placements',
        consentObtainedAt: 'consent_obtained_at',
        consentReference: 'consent_reference',
        isPlaceholder: 'is_placeholder',
        status: 'status',
        sortOrder: 'sort_order',
        scheduledFor: 'scheduled_for',
      }),
    ),
  statusOf: (input) => statusOf(input as Input),
  // The database CHECK is the gate of record for consent (every path, the cron included);
  // this says it on the field first.
  assertPublishable: (row) => {
    requireBilingual(row, 'quote', 'Quote');
    requireBilingual(row, 'author_name', 'Author name');
    refusePlaceholder(row, 'quote');
    if (!row['consent_obtained_at']) {
      throw new ValidationError(
        'record when the person agreed to be quoted before publishing',
        'consentObtainedAt',
      );
    }
  },
};

// ── Navigation ──────────────────────────────────────────────────────────────────

export const navigationResource: ResourceConfig = {
  table: 'navigation',
  entity: 'nav_item',
  writeCap: 'nav.edit',
  listColumns: 'id,location,parent_id,label,href,visible,is_key,sort_order,version',
  columns:
    'id,location,parent_id,label,href,visible,is_key,sort_order,version,created_at,updated_at',
  orderBy: { column: 'sort_order', ascending: true },
  filterableColumns: ['location'],
  createSchema: NavItemWriteSchema,
  updateSchema: NavItemUpdateSchema,
  constraintFields: {
    navigation_one_key_per_location: {
      field: 'isKey',
      message: 'This menu already has a key link — untick it there first, then tick this one.',
    },
  },
  toRow: (input) => {
    const values = pick(input as Input, {
      location: 'location',
      parentId: 'parent_id',
      label: 'label',
      href: 'href',
      visible: 'visible',
      isKey: 'is_key',
      sortOrder: 'sort_order',
    });
    if ('href' in values) {
      // Nav links render into `<a href>` on every public page. Same scheme allowlist as
      // rich-text links, because a `javascript:` nav item would be sitewide, not
      // confined to one article.
      const href = sanitizeHref(values['href']);
      if (!href) throw new ValidationError('unsupported link scheme', 'href');
      values['href'] = href;
    }
    return values;
  },
};

// ── Redirects (Admin + SEO) ─────────────────────────────────────────────────────

export const redirectResource: ResourceConfig = {
  table: 'redirects',
  entity: 'redirect',
  writeCap: 'redirects.manage',
  listColumns: 'id,source_path,target_path,status,version,created_at',
  columns: 'id,source_path,target_path,status,version,created_at,updated_at',
  orderBy: { column: 'source_path', ascending: true },
  searchColumn: 'source_path',
  createSchema: RedirectWriteSchema,
  updateSchema: RedirectUpdateSchema,
  toRow: (input) => {
    const values = pick(input as Input, {
      sourcePath: 'source_path',
      targetPath: 'target_path',
      status: 'status',
    });
    // A rule whose source equals its target is an infinite redirect loop, and the
    // middleware consults this table on EVERY public request — so one bad row is a
    // sitewide outage, not a broken page.
    if (
      typeof values['source_path'] === 'string' &&
      typeof values['target_path'] === 'string' &&
      values['source_path'] === values['target_path']
    ) {
      throw new ValidationError('a redirect cannot point at itself', 'targetPath');
    }
    if (typeof values['source_path'] === 'string' && values['source_path'].startsWith('/admin')) {
      throw new ValidationError('cannot redirect /admin paths', 'sourcePath');
    }
    return values;
  },
};

// ── Media ───────────────────────────────────────────────────────────────────────

export const mediaResource: ResourceConfig = {
  table: 'media_assets',
  entity: 'media_asset',
  writeCap: 'media.write',
  readCaps: ['media.write'],
  // 'meta' is included so the SEO role (media.write: 'meta only') can read the library
  // to attach alt text. The metadata-only WRITE path is its own endpoint.
  readAccess: ['full', 'meta'],
  listColumns:
    'id,kind,provider,storage_path,folder,alt,tags,width,height,ref_count,version,created_at',
  columns:
    'id,kind,provider,storage_path,folder,alt,tags,width,height,mime_type,size_bytes,stream_uid,ref_count,version,created_at,updated_at',
  orderBy: { column: 'created_at', ascending: false },
  searchColumn: 'storage_path',
  filterableColumns: ['kind', 'folder'],
  createSchema: MediaWriteSchema,
  updateSchema: MediaUpdateSchema,
  toRow: (input) =>
    pick(input as Input, {
      kind: 'kind',
      provider: 'provider',
      storagePath: 'storage_path',
      folder: 'folder',
      alt: 'alt',
      tags: 'tags',
      width: 'width',
      height: 'height',
      mimeType: 'mime_type',
      sizeBytes: 'size_bytes',
      streamUid: 'stream_uid',
    }),
  // A static asset names a key of the build-time registry, and only a key that exists: an
  // unknown key would be a row the public site silently cannot render.
  assertWritable: (merged, { changed }) => {
    if (!('provider' in changed) && !('storage_path' in changed)) return;
    if (merged['provider'] === 'static' && !isStaticMediaKey(String(merged['storage_path']))) {
      throw new ValidationError('not a still shipped with the site', 'storagePath');
    }
  },
  // The picker shows thumbnails; a static still's built asset URL is one (the admin is
  // exempt from the public image budget, and these frames are ≤ 70 KB).
  fromRow: (row) => ({
    ...row,
    thumb_url:
      row['provider'] === 'static' ? (staticImage(String(row['storage_path']))?.src ?? null) : null,
  }),
};

// ── Theme (Admin + Developer) ───────────────────────────────────────────────────

export const themeResource: ResourceConfig = {
  table: 'custom_themes',
  entity: 'custom_theme',
  writeCap: 'theme.edit',
  listColumns: 'id,name,is_active,version,updated_at',
  columns: 'id,name,tokens,is_active,version,created_at,updated_at',
  orderBy: { column: 'name', ascending: true },
  searchColumn: 'name',
  createSchema: ThemeWriteSchema,
  updateSchema: ThemeUpdateSchema,
  toRow: (input) => pick(input as Input, { name: 'name', tokens: 'tokens', isActive: 'is_active' }),
  afterWrite: async ({ auth, sb, row, input }) => {
    if (input['isActive'] !== true) return;
    // Exactly one active theme. Done after the write rather than in a transaction
    // because PostgREST has no multi-statement transaction — the window where two
    // themes are briefly active resolves to "the newly-activated one wins", which is
    // the intent either way.
    await sb
      .from('custom_themes')
      .update({ is_active: false })
      .eq('tenant_id', auth.tenantId)
      .neq('id', String(row['id']));
  },
};

// ── AI Style-Finder authoring ───────────────────────────────────────────────────

export const aiQuestionResource: ResourceConfig = {
  table: 'ai_questions',
  entity: 'ai_question',
  writeCap: 'ai.editContent',
  listColumns: 'id,slug,prompt,input_type,status,sort_order,version,updated_at',
  columns:
    'id,slug,prompt,help_text,input_type,options,status,sort_order,version,created_at,updated_at',
  orderBy: { column: 'sort_order', ascending: true },
  searchColumn: 'slug',
  createSchema: AiQuestionWriteSchema,
  updateSchema: AiQuestionUpdateSchema,
  toRow: (input) =>
    pick(input as Input, {
      slug: 'slug',
      prompt: 'prompt',
      helpText: 'help_text',
      inputType: 'input_type',
      options: 'options',
      status: 'status',
      sortOrder: 'sort_order',
    }),
  statusOf: (input) => statusOf(input as Input),
  assertPublishable: (row) => requireBilingual(row, 'prompt', 'Question prompt'),
};

export const aiStyleResource: ResourceConfig = {
  table: 'ai_styles',
  entity: 'ai_style',
  writeCap: 'ai.editContent',
  listColumns: 'id,slug,name,status,sort_order,version,updated_at',
  columns:
    'id,slug,name,description,traits,image_url,status,sort_order,version,created_at,updated_at',
  orderBy: { column: 'sort_order', ascending: true },
  searchColumn: 'slug',
  createSchema: AiStyleWriteSchema,
  updateSchema: AiStyleUpdateSchema,
  toRow: (input) =>
    pick(input as Input, {
      slug: 'slug',
      name: 'name',
      description: 'description',
      traits: 'traits',
      imageUrl: 'image_url',
      status: 'status',
      sortOrder: 'sort_order',
    }),
  statusOf: (input) => statusOf(input as Input),
  assertPublishable: (row) => requireBilingual(row, 'name', 'Style name'),
};
