import type { LocalizedDoc } from '@schemas/tiptap';
import type { ContentStatus } from '@schemas/primitives';
import {
  AiQuestionUpdateSchema,
  AiQuestionWriteSchema,
  AiStyleUpdateSchema,
  AiStyleWriteSchema,
  CategoryUpdateSchema,
  CategoryWriteSchema,
  CertificationUpdateSchema,
  CertificationWriteSchema,
  MediaUpdateSchema,
  MediaWriteSchema,
  NavItemUpdateSchema,
  NavItemWriteSchema,
  PageUpdateSchema,
  PageWriteSchema,
  PartnerLogoUpdateSchema,
  PartnerLogoWriteSchema,
  PortfolioUpdateSchema,
  PortfolioWriteSchema,
  PostUpdateSchema,
  PostWriteSchema,
  RedirectUpdateSchema,
  RedirectWriteSchema,
  SectionUpdateSchema,
  SectionWriteSchema,
  ServiceUpdateSchema,
  ServiceWriteSchema,
  StatisticUpdateSchema,
  StatisticWriteSchema,
  TeamMemberUpdateSchema,
  TeamMemberWriteSchema,
  ThemeUpdateSchema,
  ThemeWriteSchema,
} from '@schemas/admin';
import { renderTiptapToHtml, readingMinutes, sanitizeHref } from '@/lib/content/tiptap';
import { ValidationError } from './errors';
import type { ResourceConfig, ResourcePayload } from './resource';

// One config per CRUD entity. Everything structural (tenant scoping, authz, audit,
// optimistic locking) lives in resource.ts; this file is only "which table, which
// columns, which capability, how does the wire shape map to columns".

type Input = ResourcePayload;

/**
 * camelCase input → snake_case column patch.
 *
 * This is the allowlist that makes mass-assignment impossible: a client can send
 * `{"tenant_id": "<someone else's>"}` or `{"version": 999}` all it likes, because only
 * keys named in `map` are ever copied into the object handed to the query builder.
 * `undefined` is skipped so a PATCH touches exactly the fields it sent — `null` is
 * kept, because "clear this field" is a real edit.
 */
function pick(input: Input, map: Record<string, string>): Input {
  const out: Input = {};
  for (const [key, column] of Object.entries(map)) {
    if (key in input && input[key] !== undefined) out[column] = input[key];
  }
  return out;
}

/** Locale-keyed Tiptap JSON → locale-keyed sanitised HTML (the render-time cache). */
function deriveBodyHtml(body: unknown): Record<string, string> | null {
  if (!body || typeof body !== 'object') return null;
  const doc = body as Partial<LocalizedDoc>;
  const out: Record<string, string> = {};
  if (doc.en) out['en'] = renderTiptapToHtml(doc.en);
  if (doc.ar) out['ar'] = renderTiptapToHtml(doc.ar);
  return out;
}

/**
 * Adds the derived HTML cache alongside the stored JSON.
 *
 * Both are written in the same statement on purpose. If `body_html` were regenerated
 * lazily at render time, the public Tier-A page would be re-sanitising on every cache
 * miss (a per-request cost on the latency-critical path), and if it were regenerated by
 * a separate call the two could drift — leaving stored JSON that says one thing and
 * cached HTML that says another, with the HTML being what visitors actually see.
 */
function withBodyHtml(values: Input, input: Input): Input {
  if (!('body' in input) || input['body'] === undefined) return values;
  return { ...values, body_html: deriveBodyHtml(input['body']) };
}

const statusOf = (input: Input): ContentStatus | undefined =>
  typeof input['status'] === 'string' ? (input['status'] as ContentStatus) : undefined;

/** Publishing sets published_at once and never rewrites it (truthful dates, Pillar 3). */
function publishStamp(values: Input): Input {
  return values['status'] === 'published'
    ? { ...values, published_at: new Date().toISOString() }
    : values;
}

function requireBilingual(row: Input, column: string, label: string): void {
  const value = row[column];
  const record = (value ?? {}) as Record<string, unknown>;
  if (!record['en'] || !record['ar']) {
    throw new ValidationError(`${label} must have both English and Arabic before publishing`);
  }
}

// ── Services ────────────────────────────────────────────────────────────────────

export const serviceResource: ResourceConfig = {
  table: 'services',
  entity: 'service',
  writeCap: 'services.write',
  // SEO can list/read a service to author its meta, but not write the row itself.
  readCaps: ['services.write', 'seo.entityMeta'],
  listColumns: 'id,slug,title,status,is_teaser,sort_order,version,updated_at',
  columns:
    'id,slug,title,blurb,body,body_html,hero_video_uid,category,status,is_teaser,sort_order,version,published_at,scheduled_for,created_at,updated_at',
  orderBy: { column: 'sort_order', ascending: true },
  searchColumn: 'slug',
  createSchema: ServiceWriteSchema,
  updateSchema: ServiceUpdateSchema,
  toRow: (input) =>
    publishStamp(
      withBodyHtml(
        pick(input as Input, {
          slug: 'slug',
          title: 'title',
          blurb: 'blurb',
          body: 'body',
          heroVideoUid: 'hero_video_uid',
          category: 'category',
          status: 'status',
          isTeaser: 'is_teaser',
          sortOrder: 'sort_order',
          scheduledFor: 'scheduled_for',
        }),
        input as Input,
      ),
    ),
  statusOf: (input) => statusOf(input as Input),
  assertPublishable: (row) => requireBilingual(row, 'title', 'Service title'),
};

// ── Blog ────────────────────────────────────────────────────────────────────────

export const postResource: ResourceConfig = {
  table: 'blog_posts',
  entity: 'blog_post',
  writeCap: 'blog.write',
  readCaps: ['blog.write', 'seo.entityMeta'],
  listColumns: 'id,slug,title,status,published_at,scheduled_for,version,updated_at',
  columns:
    'id,slug,title,excerpt,body,body_html,author_id,category_id,cover_image_url,status,published_at,scheduled_for,reading_minutes,version,created_at,updated_at',
  orderBy: { column: 'updated_at', ascending: false },
  searchColumn: 'slug',
  filterableColumns: ['category_id', 'author_id'],
  createSchema: PostWriteSchema,
  updateSchema: PostUpdateSchema,
  toRow: (input) => {
    const values = publishStamp(
      withBodyHtml(
        pick(input as Input, {
          slug: 'slug',
          title: 'title',
          excerpt: 'excerpt',
          body: 'body',
          authorId: 'author_id',
          categoryId: 'category_id',
          coverImageUrl: 'cover_image_url',
          status: 'status',
          scheduledFor: 'scheduled_for',
        }),
        input as Input,
      ),
    );
    const body = (input as Input)['body'] as Partial<LocalizedDoc> | undefined;
    // Reading time is DERIVED, never authored: an editor-supplied number drifts from
    // the body the moment anyone edits it, and it is user-visible.
    return body?.en ? { ...values, reading_minutes: readingMinutes(body.en) } : values;
  },
  statusOf: (input) => statusOf(input as Input),
  assertPublishable: (row) => {
    requireBilingual(row, 'title', 'Post title');
    // CLAUDE.md Pillar 3: "E-E-A-T author pages — no anonymous authorship". A published
    // post with a null author is the exact thing that rule forbids, so it is refused
    // here rather than being allowed to reach the JSON-LD builder and emit an Article
    // with no `author`.
    if (!row['author_id']) {
      throw new ValidationError('a published post must have an author (E-E-A-T)', 'authorId');
    }
  },
};

// ── Portfolio ───────────────────────────────────────────────────────────────────

export const portfolioResource: ResourceConfig = {
  table: 'portfolio',
  entity: 'portfolio',
  writeCap: 'portfolio.write',
  readCaps: ['portfolio.write', 'seo.entityMeta'],
  listColumns: 'id,slug,title,status,sort_order,version,updated_at',
  columns:
    'id,slug,title,summary,body,body_html,status,sort_order,version,published_at,scheduled_for,created_at,updated_at',
  orderBy: { column: 'sort_order', ascending: true },
  searchColumn: 'slug',
  createSchema: PortfolioWriteSchema,
  updateSchema: PortfolioUpdateSchema,
  toRow: (input) =>
    publishStamp(
      withBodyHtml(
        pick(input as Input, {
          slug: 'slug',
          title: 'title',
          summary: 'summary',
          body: 'body',
          status: 'status',
          sortOrder: 'sort_order',
          scheduledFor: 'scheduled_for',
        }),
        input as Input,
      ),
    ),
  statusOf: (input) => statusOf(input as Input),
  assertPublishable: (row) => requireBilingual(row, 'title', 'Case study title'),
  afterWrite: async ({ auth, sb, row, input }) => {
    const serviceIds = (input as Input)['serviceIds'];
    if (!Array.isArray(serviceIds)) return;
    const portfolioId = String(row['id']);
    // Replace-the-set semantics. Both statements are tenant-scoped: the DELETE so it
    // cannot clear another tenant's links, the INSERT so it cannot create one.
    await sb
      .from('portfolio_services')
      .delete()
      .eq('tenant_id', auth.tenantId)
      .eq('portfolio_id', portfolioId);
    if (serviceIds.length === 0) return;
    await sb.from('portfolio_services').insert(
      serviceIds.map((serviceId) => ({
        tenant_id: auth.tenantId,
        portfolio_id: portfolioId,
        service_id: String(serviceId),
      })),
    );
  },
};

// ── Pages & sections ────────────────────────────────────────────────────────────

export const pageResource: ResourceConfig = {
  table: 'pages',
  entity: 'page',
  writeCap: 'pages.write',
  readCaps: ['pages.write', 'seo.entityMeta', 'maintenance.manage'],
  listColumns: 'id,slug,title,status,nav_visible,version,updated_at',
  columns:
    'id,slug,title,status,nav_visible,version,published_at,scheduled_for,created_at,updated_at',
  orderBy: { column: 'slug', ascending: true },
  searchColumn: 'slug',
  createSchema: PageWriteSchema,
  updateSchema: PageUpdateSchema,
  toRow: (input) =>
    publishStamp(
      pick(input as Input, {
        slug: 'slug',
        title: 'title',
        status: 'status',
        navVisible: 'nav_visible',
        scheduledFor: 'scheduled_for',
      }),
    ),
  statusOf: (input) => statusOf(input as Input),
  assertPublishable: (row) => requireBilingual(row, 'title', 'Page title'),
};

export const sectionResource: ResourceConfig = {
  table: 'page_sections',
  entity: 'page_section',
  writeCap: 'pages.write',
  listColumns: 'id,page_id,type,visible,sort_order,version,updated_at',
  columns: 'id,page_id,type,content,style,visible,sort_order,version,created_at,updated_at',
  orderBy: { column: 'sort_order', ascending: true },
  filterableColumns: ['page_id'],
  createSchema: SectionWriteSchema,
  updateSchema: SectionUpdateSchema,
  toRow: (input) =>
    pick(input as Input, {
      pageId: 'page_id',
      type: 'type',
      content: 'content',
      style: 'style',
      visible: 'visible',
      sortOrder: 'sort_order',
    }),
};

// ── Taxonomy & about-page entities ──────────────────────────────────────────────

export const categoryResource: ResourceConfig = {
  table: 'categories',
  entity: 'category',
  writeCap: 'categories.manage',
  readCaps: ['categories.manage', 'blog.write', 'seo.entityMeta'],
  listColumns: 'id,slug,name,version',
  columns: 'id,slug,name,version,created_at,updated_at',
  orderBy: { column: 'slug', ascending: true },
  searchColumn: 'slug',
  createSchema: CategoryWriteSchema,
  updateSchema: CategoryUpdateSchema,
  toRow: (input) => pick(input as Input, { slug: 'slug', name: 'name' }),
};

export const teamResource: ResourceConfig = {
  table: 'team_members',
  entity: 'team_member',
  writeCap: 'blog.write',
  readCaps: ['blog.write', 'services.write', 'seo.entityMeta'],
  listColumns: 'id,slug,name,status,sort_order,version,updated_at',
  columns:
    'id,slug,name,bio,avatar_url,profile_user_id,status,sort_order,version,created_at,updated_at',
  orderBy: { column: 'sort_order', ascending: true },
  searchColumn: 'slug',
  createSchema: TeamMemberWriteSchema,
  updateSchema: TeamMemberUpdateSchema,
  toRow: (input) =>
    pick(input as Input, {
      slug: 'slug',
      name: 'name',
      bio: 'bio',
      avatarUrl: 'avatar_url',
      profileUserId: 'profile_user_id',
      status: 'status',
      sortOrder: 'sort_order',
    }),
  statusOf: (input) => statusOf(input as Input),
  assertPublishable: (row) => requireBilingual(row, 'name', 'Author name'),
};

export const certificationResource: ResourceConfig = {
  table: 'certifications',
  entity: 'certification',
  writeCap: 'services.write',
  listColumns: 'id,slug,name,year,status,sort_order,version,updated_at',
  columns: 'id,slug,name,issuer,year,logo_url,status,sort_order,version,created_at,updated_at',
  orderBy: { column: 'sort_order', ascending: true },
  searchColumn: 'slug',
  createSchema: CertificationWriteSchema,
  updateSchema: CertificationUpdateSchema,
  toRow: (input) =>
    pick(input as Input, {
      slug: 'slug',
      name: 'name',
      issuer: 'issuer',
      year: 'year',
      logoUrl: 'logo_url',
      status: 'status',
      sortOrder: 'sort_order',
    }),
  statusOf: (input) => statusOf(input as Input),
  assertPublishable: (row) => requireBilingual(row, 'name', 'Certification name'),
};

export const statisticResource: ResourceConfig = {
  table: 'statistics',
  entity: 'statistic',
  writeCap: 'services.write',
  listColumns: 'id,slug,label,value,status,sort_order,version,updated_at',
  columns: 'id,slug,label,value,status,sort_order,version,created_at,updated_at',
  orderBy: { column: 'sort_order', ascending: true },
  searchColumn: 'slug',
  createSchema: StatisticWriteSchema,
  updateSchema: StatisticUpdateSchema,
  toRow: (input) =>
    pick(input as Input, {
      slug: 'slug',
      label: 'label',
      value: 'value',
      status: 'status',
      sortOrder: 'sort_order',
    }),
  statusOf: (input) => statusOf(input as Input),
  assertPublishable: (row) => requireBilingual(row, 'label', 'Statistic label'),
};

export const partnerLogoResource: ResourceConfig = {
  table: 'partner_logos',
  entity: 'partner_logo',
  writeCap: 'services.write',
  listColumns: 'id,name,logo_url,visible,sort_order,version',
  columns: 'id,name,logo_url,scale,offset_y,visible,sort_order,version',
  orderBy: { column: 'sort_order', ascending: true },
  searchColumn: 'name',
  createSchema: PartnerLogoWriteSchema,
  updateSchema: PartnerLogoUpdateSchema,
  toRow: (input) =>
    pick(input as Input, {
      name: 'name',
      logoUrl: 'logo_url',
      scale: 'scale',
      offsetY: 'offset_y',
      visible: 'visible',
      sortOrder: 'sort_order',
    }),
};

// ── Navigation ──────────────────────────────────────────────────────────────────

export const navigationResource: ResourceConfig = {
  table: 'navigation',
  entity: 'nav_item',
  writeCap: 'nav.edit',
  listColumns: 'id,location,parent_id,label,href,visible,sort_order,version',
  columns: 'id,location,parent_id,label,href,visible,sort_order,version,created_at,updated_at',
  orderBy: { column: 'sort_order', ascending: true },
  filterableColumns: ['location'],
  createSchema: NavItemWriteSchema,
  updateSchema: NavItemUpdateSchema,
  toRow: (input) => {
    const values = pick(input as Input, {
      location: 'location',
      parentId: 'parent_id',
      label: 'label',
      href: 'href',
      visible: 'visible',
      sortOrder: 'sort_order',
    });
    if ('href' in values) {
      // Nav links render into `<a href>` on every public page. Same scheme allowlist as
      // rich-text links, because a `javascript:` nav item would be sitewide, not
      // confined to one article.
      const href = sanitizeHref(values['href']);
      if (!href) throw new ValidationError('unsupported link scheme', 'href');
      values['href'] = href;
    }
    return values;
  },
};

// ── Redirects (Admin + SEO) ─────────────────────────────────────────────────────

export const redirectResource: ResourceConfig = {
  table: 'redirects',
  entity: 'redirect',
  writeCap: 'redirects.manage',
  listColumns: 'id,source_path,target_path,status,version,created_at',
  columns: 'id,source_path,target_path,status,version,created_at,updated_at',
  orderBy: { column: 'source_path', ascending: true },
  searchColumn: 'source_path',
  createSchema: RedirectWriteSchema,
  updateSchema: RedirectUpdateSchema,
  toRow: (input) => {
    const values = pick(input as Input, {
      sourcePath: 'source_path',
      targetPath: 'target_path',
      status: 'status',
    });
    // A rule whose source equals its target is an infinite redirect loop, and the
    // middleware consults this table on EVERY public request — so one bad row is a
    // sitewide outage, not a broken page.
    if (
      typeof values['source_path'] === 'string' &&
      typeof values['target_path'] === 'string' &&
      values['source_path'] === values['target_path']
    ) {
      throw new ValidationError('a redirect cannot point at itself', 'targetPath');
    }
    if (typeof values['source_path'] === 'string' && values['source_path'].startsWith('/admin')) {
      throw new ValidationError('cannot redirect /admin paths', 'sourcePath');
    }
    return values;
  },
};

// ── Media ───────────────────────────────────────────────────────────────────────

export const mediaResource: ResourceConfig = {
  table: 'media_assets',
  entity: 'media_asset',
  writeCap: 'media.write',
  readCaps: ['media.write'],
  // 'meta' is included so the SEO role (media.write: 'meta only') can read the library
  // to attach alt text. The metadata-only WRITE path is its own endpoint.
  readAccess: ['full', 'meta'],
  listColumns: 'id,kind,storage_path,folder,alt,tags,width,height,ref_count,version,created_at',
  columns:
    'id,kind,storage_path,folder,alt,tags,width,height,mime_type,size_bytes,stream_uid,ref_count,version,created_at,updated_at',
  orderBy: { column: 'created_at', ascending: false },
  searchColumn: 'storage_path',
  filterableColumns: ['kind', 'folder'],
  createSchema: MediaWriteSchema,
  updateSchema: MediaUpdateSchema,
  toRow: (input) =>
    pick(input as Input, {
      kind: 'kind',
      storagePath: 'storage_path',
      folder: 'folder',
      alt: 'alt',
      tags: 'tags',
      width: 'width',
      height: 'height',
      mimeType: 'mime_type',
      sizeBytes: 'size_bytes',
      streamUid: 'stream_uid',
    }),
};

// ── Theme (Admin + Developer) ───────────────────────────────────────────────────

export const themeResource: ResourceConfig = {
  table: 'custom_themes',
  entity: 'custom_theme',
  writeCap: 'theme.edit',
  listColumns: 'id,name,is_active,version,updated_at',
  columns: 'id,name,tokens,is_active,version,created_at,updated_at',
  orderBy: { column: 'name', ascending: true },
  searchColumn: 'name',
  createSchema: ThemeWriteSchema,
  updateSchema: ThemeUpdateSchema,
  toRow: (input) => pick(input as Input, { name: 'name', tokens: 'tokens', isActive: 'is_active' }),
  afterWrite: async ({ auth, sb, row, input }) => {
    if (input['isActive'] !== true) return;
    // Exactly one active theme. Done after the write rather than in a transaction
    // because PostgREST has no multi-statement transaction — the window where two
    // themes are briefly active resolves to "the newly-activated one wins", which is
    // the intent either way.
    await sb
      .from('custom_themes')
      .update({ is_active: false })
      .eq('tenant_id', auth.tenantId)
      .neq('id', String(row['id']));
  },
};

// ── AI Style-Finder authoring ───────────────────────────────────────────────────

export const aiQuestionResource: ResourceConfig = {
  table: 'ai_questions',
  entity: 'ai_question',
  writeCap: 'ai.editContent',
  listColumns: 'id,slug,prompt,input_type,status,sort_order,version,updated_at',
  columns:
    'id,slug,prompt,help_text,input_type,options,status,sort_order,version,created_at,updated_at',
  orderBy: { column: 'sort_order', ascending: true },
  searchColumn: 'slug',
  createSchema: AiQuestionWriteSchema,
  updateSchema: AiQuestionUpdateSchema,
  toRow: (input) =>
    pick(input as Input, {
      slug: 'slug',
      prompt: 'prompt',
      helpText: 'help_text',
      inputType: 'input_type',
      options: 'options',
      status: 'status',
      sortOrder: 'sort_order',
    }),
  statusOf: (input) => statusOf(input as Input),
  assertPublishable: (row) => requireBilingual(row, 'prompt', 'Question prompt'),
};

export const aiStyleResource: ResourceConfig = {
  table: 'ai_styles',
  entity: 'ai_style',
  writeCap: 'ai.editContent',
  listColumns: 'id,slug,name,status,sort_order,version,updated_at',
  columns:
    'id,slug,name,description,traits,image_url,status,sort_order,version,created_at,updated_at',
  orderBy: { column: 'sort_order', ascending: true },
  searchColumn: 'slug',
  createSchema: AiStyleWriteSchema,
  updateSchema: AiStyleUpdateSchema,
  toRow: (input) =>
    pick(input as Input, {
      slug: 'slug',
      name: 'name',
      description: 'description',
      traits: 'traits',
      imageUrl: 'image_url',
      status: 'status',
      sortOrder: 'sort_order',
    }),
  statusOf: (input) => statusOf(input as Input),
  assertPublishable: (row) => requireBilingual(row, 'name', 'Style name'),
};
